// Code generated by Fern. DO NOT EDIT.

package notifications

import (
	kard "github.com/KardFinancial/kard-go-sdk/v8"
	core "github.com/KardFinancial/kard-go-sdk/v8/core"
	internal "github.com/KardFinancial/kard-go-sdk/v8/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	400: func(apiError *core.APIError) error {
		return &kard.InvalidRequest{
			APIError: apiError,
		}
	},
	401: func(apiError *core.APIError) error {
		return &kard.UnauthorizedError{
			APIError: apiError,
		}
	},
	500: func(apiError *core.APIError) error {
		return &kard.InternalServerError{
			APIError: apiError,
		}
	},
	409: func(apiError *core.APIError) error {
		return &kard.ConflictError{
			APIError: apiError,
		}
	},
	404: func(apiError *core.APIError) error {
		return &kard.DoesNotExistError{
			APIError: apiError,
		}
	},
}
