// Code generated by Fern. DO NOT EDIT.

package notifications_subscriptions_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	kard "github.com/KardFinancial/kard-go-sdk/v7"
	client "github.com/KardFinancial/kard-go-sdk/v7/client"
	notifications "github.com/KardFinancial/kard-go-sdk/v7/notifications"
	option "github.com/KardFinancial/kard-go-sdk/v7/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestNotificationsSubscriptionsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &notifications.GetSubscriptionsRequest{}
	_, invocationErr := client.Notifications.Subscriptions.Get(
		context.TODO(),
		"organization-123",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestNotificationsSubscriptionsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestNotificationsSubscriptionsGetWithWireMock", "GET", "/v2/issuers/organization-123/subscriptions", nil, 1)
}

func TestNotificationsSubscriptionsCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &notifications.SubscriptionRequestBody{
		Data: []*notifications.SubscriptionRequestUnion{
			&notifications.SubscriptionRequestUnion{
				Subscription: &notifications.SubscriptionRequest{
					Attributes: &notifications.SubscriptionRequestAttributes{
						EventName:  kard.NotificationTypeEarnedRewardApproved,
						WebhookUrl: "https://webhookUrl.com/post",
						Enabled:    true,
					},
				},
			},
		},
	}
	_, invocationErr := client.Notifications.Subscriptions.Create(
		context.TODO(),
		"organization-123",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestNotificationsSubscriptionsCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestNotificationsSubscriptionsCreateWithWireMock", "POST", "/v2/issuers/organization-123/subscriptions", nil, 1)
}

func TestNotificationsSubscriptionsUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &notifications.UpdateSubscriptionRequestBody{
		Data: &notifications.UpdateSubscriptionRequestUnion{
			Subscription: &notifications.UpdateSubscriptionRequest{
				Attributes: &notifications.UpdateSubscriptionRequestAttributes{
					EventName: kard.NotificationTypeEarnedRewardApproved.Ptr(),
					WebhookUrl: kard.String(
						"https://webhookUrl.com/post",
					),
					Enabled: kard.Bool(
						true,
					),
				},
			},
		},
	}
	_, invocationErr := client.Notifications.Subscriptions.Update(
		context.TODO(),
		"organization-123",
		"subscription-123",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestNotificationsSubscriptionsUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestNotificationsSubscriptionsUpdateWithWireMock", "PATCH", "/v2/issuers/organization-123/subscriptions/subscription-123", nil, 1)
}
