// Code generated by Fern. DO NOT EDIT.

package organizations_content_strategies_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	kard "github.com/KardFinancial/kard-go-sdk/v7"
	client "github.com/KardFinancial/kard-go-sdk/v7/client"
	option "github.com/KardFinancial/kard-go-sdk/v7/option"
	organizations "github.com/KardFinancial/kard-go-sdk/v7/organizations"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestOrganizationsContentStrategiesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &organizations.CreateContentStrategyRequestBody{
		Data: &organizations.CreateContentStrategyRequestData{
			Attributes: &organizations.CreateContentStrategyAttributes{
				Name: "Featured Travel",
				Sort: organizations.ContentStrategySortHighestCashback.Ptr(),
				Categories: []kard.CategoryOption{
					kard.CategoryOptionTravel,
				},
				CategoryExclusions: []kard.CategoryOption{
					kard.CategoryOptionGas,
				},
				MerchantExclusions: []string{
					"merchant-abc",
				},
			},
		},
	}
	_, invocationErr := client.Organizations.ContentStrategies.Create(
		context.TODO(),
		"org-123",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationsContentStrategiesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationsContentStrategiesCreateWithWireMock", "POST", "/v2/issuers/org-123/contentStrategies", nil, 1)
}

func TestOrganizationsContentStrategiesListWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &organizations.ListContentStrategiesRequest{}
	_, invocationErr := client.Organizations.ContentStrategies.List(
		context.TODO(),
		"organizationId",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationsContentStrategiesListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationsContentStrategiesListWithWireMock", "GET", "/v2/issuers/organizationId/contentStrategies", nil, 1)
}

func TestOrganizationsContentStrategiesGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Organizations.ContentStrategies.Get(
		context.TODO(),
		"organizationId",
		"contentStrategyId",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationsContentStrategiesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationsContentStrategiesGetWithWireMock", "GET", "/v2/issuers/organizationId/contentStrategies/contentStrategyId", nil, 1)
}

func TestOrganizationsContentStrategiesUpdateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &organizations.UpdateContentStrategyRequestBody{
		Data: &organizations.UpdateContentStrategyRequestData{
			Attributes: &organizations.UpdateContentStrategyAttributes{
				Name: "name",
				Categories: []kard.CategoryOption{
					kard.CategoryOptionArtsEntertainment,
					kard.CategoryOptionArtsEntertainment,
				},
				CategoryExclusions: []kard.CategoryOption{
					kard.CategoryOptionArtsEntertainment,
					kard.CategoryOptionArtsEntertainment,
				},
				MerchantExclusions: []string{
					"merchantExclusions",
					"merchantExclusions",
				},
			},
		},
	}
	_, invocationErr := client.Organizations.ContentStrategies.Update(
		context.TODO(),
		"organizationId",
		"contentStrategyId",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationsContentStrategiesUpdateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationsContentStrategiesUpdateWithWireMock", "PUT", "/v2/issuers/organizationId/contentStrategies/contentStrategyId", nil, 1)
}

func TestOrganizationsContentStrategiesDeleteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Organizations.ContentStrategies.Delete(
		context.TODO(),
		"organizationId",
		"contentStrategyId",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestOrganizationsContentStrategiesDeleteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestOrganizationsContentStrategiesDeleteWithWireMock", "DELETE", "/v2/issuers/organizationId/contentStrategies/contentStrategyId", nil, 1)
}
