// Code generated by Fern. DO NOT EDIT.

package rewards

import (
	context "context"
	os "os"

	kard "github.com/KardFinancial/kard-go-sdk/v5"
	core "github.com/KardFinancial/kard-go-sdk/v5/core"
	internal "github.com/KardFinancial/kard-go-sdk/v5/internal"
	option "github.com/KardFinancial/kard-go-sdk/v5/option"
	users "github.com/KardFinancial/kard-go-sdk/v5/users"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.ClientID == "" {
		options.ClientID = os.Getenv("KARD_CLIENT_ID")
	}
	if options.ClientSecret == "" {
		options.ClientSecret = os.Getenv("KARD_CLIENT_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieve national brand offers that a specified user is eligible for. Call this endpoint to build out your
// [targeted offers UX experience](/2024-10-01/api/getting-started#b-discover-a-lapsed-customer-clo). Local offers details
// can be found by calling the [Get Eligible Locations](/2024-10-01/api/rewards/locations).<br/>
// <b>Required scopes:</b> `rewards:read`
func (c *Client) Offers(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	request *users.GetOffersByUserRequest,
	opts ...option.RequestOption,
) (*users.OffersResponseObject, error) {
	response, err := c.WithRawResponse.Offers(
		ctx,
		organizationId,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve offers for a placement slot. Returns offers sorted by highest cash back,
// limited by the placement's available slots.<br/>
// <b>Required scopes:</b> `rewards:read`
func (c *Client) PlacementOffers(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	placementId string,
	request *users.GetOffersByPlacementRequest,
	opts ...option.RequestOption,
) (*users.OffersResponseObject, error) {
	response, err := c.WithRawResponse.PlacementOffers(
		ctx,
		organizationId,
		userId,
		placementId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve national and local geographic locations that a specified user has eligible in-store offers at. Use this endpoint to build
// out your [map-specific UX experiences](/2024-10-01/api/getting-started#c-discover-clos-near-you-map-view). Please note
// that Longitude and Latitude fields are prioritized over State, City and Zipcode and are the recommended search
// pattern.<br/>
// <br/>
// <b>Required scopes:</b> `rewards:read`
func (c *Client) Locations(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	request *users.GetLocationsByUserRequest,
	opts ...option.RequestOption,
) (*users.LocationsResponseObject, error) {
	response, err := c.WithRawResponse.Locations(
		ctx,
		organizationId,
		userId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
