// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/KardFinancial/kard-go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	auditUpdateAttributesFieldStatus                = big.NewInt(1 << 0)
	auditUpdateAttributesFieldAuditCode             = big.NewInt(1 << 1)
	auditUpdateAttributesFieldMerchantName          = big.NewInt(1 << 2)
	auditUpdateAttributesFieldAuditDescription      = big.NewInt(1 << 3)
	auditUpdateAttributesFieldTransactionID         = big.NewInt(1 << 4)
	auditUpdateAttributesFieldResolutionCode        = big.NewInt(1 << 5)
	auditUpdateAttributesFieldResolutionDescription = big.NewInt(1 << 6)
	auditUpdateAttributesFieldResolutionTimeStamp   = big.NewInt(1 << 7)
)

type AuditUpdateAttributes struct {
	// The status of the audit
	Status AuditStatus `json:"status" url:"status"`
	// Audit Code - Enum. Code to define audit.
	//
	//	<ul>
	//	  <li>`3005` : Customer is claiming cashback is incorrect - INCORRECT CASHBACK CLAIM</li>
	//	  <li>`3006` : Transaction is missing the cashback award - MISSING CASHBACK AWARD</li>
	//	  <li>`8001` : Other - check audit description</li>
	//	</ul>
	AuditCode int `json:"auditCode" url:"auditCode"`
	// The merchant name related to the transaction audit
	MerchantName string `json:"merchantName" url:"merchantName"`
	// The description of the audit
	AuditDescription string `json:"auditDescription" url:"auditDescription"`
	// The transaction ID associated with audit
	TransactionID string `json:"transactionId" url:"transactionId"`
	// Resolution Code - Enum. field is available when audit is status CLOSED.
	// <ul>
	//
	//	<li>`5001` : Transaction will be deleted</li>
	//	<li>`5002` : Settlement amount will be adjusted</li>
	//	<li>`5003` : Return amount will be adjusted</li>
	//	<li>`5004` : Reward dispute resolved</li>
	//	<li>`5005` : Transaction will be marked for writeoff</li>
	//	<li>`5006` : Transaction will be marked as rejected</li>
	//	<li>`5007` : Transaction will be resent through webhook</li>
	//	<li>`5008` : Transaction will be resent through daily file</li>
	//	<li>`5009` : No change needed</li>
	//	<li>`9001` : Ineligible item in purchase</li>
	//	<li>`9002` : Return was made</li>
	//	<li>`9003` : User ineligible for offer (usually because of participation through another program)</li>
	//	<li>`9004` : Redemption limit hit (if offer has a set number of redemptions and it isn't handled programmatically)</li>
	//	<li>`9005` : Transaction not captured</li>
	//
	// </ul>
	ResolutionCode *int `json:"resolutionCode,omitempty" url:"resolutionCode,omitempty"`
	// The resolution description; field is available when audit is status CLOSED
	ResolutionDescription *string `json:"resolutionDescription,omitempty" url:"resolutionDescription,omitempty"`
	// The resolution timestamp of when the audit was marked as status CLOSED in ISO format; available when audit is closed.
	ResolutionTimeStamp *time.Time `json:"resolutionTimeStamp,omitempty" url:"resolutionTimeStamp,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuditUpdateAttributes) GetStatus() AuditStatus {
	if a == nil {
		return ""
	}
	return a.Status
}

func (a *AuditUpdateAttributes) GetAuditCode() int {
	if a == nil {
		return 0
	}
	return a.AuditCode
}

func (a *AuditUpdateAttributes) GetMerchantName() string {
	if a == nil {
		return ""
	}
	return a.MerchantName
}

func (a *AuditUpdateAttributes) GetAuditDescription() string {
	if a == nil {
		return ""
	}
	return a.AuditDescription
}

func (a *AuditUpdateAttributes) GetTransactionID() string {
	if a == nil {
		return ""
	}
	return a.TransactionID
}

func (a *AuditUpdateAttributes) GetResolutionCode() *int {
	if a == nil {
		return nil
	}
	return a.ResolutionCode
}

func (a *AuditUpdateAttributes) GetResolutionDescription() *string {
	if a == nil {
		return nil
	}
	return a.ResolutionDescription
}

func (a *AuditUpdateAttributes) GetResolutionTimeStamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.ResolutionTimeStamp
}

func (a *AuditUpdateAttributes) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuditUpdateAttributes) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetStatus(status AuditStatus) {
	a.Status = status
	a.require(auditUpdateAttributesFieldStatus)
}

// SetAuditCode sets the AuditCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetAuditCode(auditCode int) {
	a.AuditCode = auditCode
	a.require(auditUpdateAttributesFieldAuditCode)
}

// SetMerchantName sets the MerchantName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetMerchantName(merchantName string) {
	a.MerchantName = merchantName
	a.require(auditUpdateAttributesFieldMerchantName)
}

// SetAuditDescription sets the AuditDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetAuditDescription(auditDescription string) {
	a.AuditDescription = auditDescription
	a.require(auditUpdateAttributesFieldAuditDescription)
}

// SetTransactionID sets the TransactionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetTransactionID(transactionID string) {
	a.TransactionID = transactionID
	a.require(auditUpdateAttributesFieldTransactionID)
}

// SetResolutionCode sets the ResolutionCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetResolutionCode(resolutionCode *int) {
	a.ResolutionCode = resolutionCode
	a.require(auditUpdateAttributesFieldResolutionCode)
}

// SetResolutionDescription sets the ResolutionDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetResolutionDescription(resolutionDescription *string) {
	a.ResolutionDescription = resolutionDescription
	a.require(auditUpdateAttributesFieldResolutionDescription)
}

// SetResolutionTimeStamp sets the ResolutionTimeStamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateAttributes) SetResolutionTimeStamp(resolutionTimeStamp *time.Time) {
	a.ResolutionTimeStamp = resolutionTimeStamp
	a.require(auditUpdateAttributesFieldResolutionTimeStamp)
}

func (a *AuditUpdateAttributes) UnmarshalJSON(data []byte) error {
	type embed AuditUpdateAttributes
	var unmarshaler = struct {
		embed
		ResolutionTimeStamp *internal.DateTime `json:"resolutionTimeStamp,omitempty"`
	}{
		embed: embed(*a),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*a = AuditUpdateAttributes(unmarshaler.embed)
	a.ResolutionTimeStamp = unmarshaler.ResolutionTimeStamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuditUpdateAttributes) MarshalJSON() ([]byte, error) {
	type embed AuditUpdateAttributes
	var marshaler = struct {
		embed
		ResolutionTimeStamp *internal.DateTime `json:"resolutionTimeStamp,omitempty"`
	}{
		embed:               embed(*a),
		ResolutionTimeStamp: internal.NewOptionalDateTime(a.ResolutionTimeStamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuditUpdateAttributes) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	auditUpdateDataFieldID            = big.NewInt(1 << 0)
	auditUpdateDataFieldAttributes    = big.NewInt(1 << 1)
	auditUpdateDataFieldRelationships = big.NewInt(1 << 2)
)

type AuditUpdateData struct {
	// The internal ID of the notification
	ID            string                    `json:"id" url:"id"`
	Attributes    *AuditUpdateAttributes    `json:"attributes" url:"attributes"`
	Relationships *AuditUpdateRelationships `json:"relationships" url:"relationships"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuditUpdateData) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AuditUpdateData) GetAttributes() *AuditUpdateAttributes {
	if a == nil {
		return nil
	}
	return a.Attributes
}

func (a *AuditUpdateData) GetRelationships() *AuditUpdateRelationships {
	if a == nil {
		return nil
	}
	return a.Relationships
}

func (a *AuditUpdateData) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuditUpdateData) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateData) SetID(id string) {
	a.ID = id
	a.require(auditUpdateDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateData) SetAttributes(attributes *AuditUpdateAttributes) {
	a.Attributes = attributes
	a.require(auditUpdateDataFieldAttributes)
}

// SetRelationships sets the Relationships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateData) SetRelationships(relationships *AuditUpdateRelationships) {
	a.Relationships = relationships
	a.require(auditUpdateDataFieldRelationships)
}

func (a *AuditUpdateData) UnmarshalJSON(data []byte) error {
	type unmarshaler AuditUpdateData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuditUpdateData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuditUpdateData) MarshalJSON() ([]byte, error) {
	type embed AuditUpdateData
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuditUpdateData) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	auditUpdateRelationshipsFieldUser  = big.NewInt(1 << 0)
	auditUpdateRelationshipsFieldAudit = big.NewInt(1 << 1)
)

type AuditUpdateRelationships struct {
	User  *RelationshipSingle `json:"user" url:"user"`
	Audit *RelationshipSingle `json:"audit" url:"audit"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AuditUpdateRelationships) GetUser() *RelationshipSingle {
	if a == nil {
		return nil
	}
	return a.User
}

func (a *AuditUpdateRelationships) GetAudit() *RelationshipSingle {
	if a == nil {
		return nil
	}
	return a.Audit
}

func (a *AuditUpdateRelationships) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AuditUpdateRelationships) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateRelationships) SetUser(user *RelationshipSingle) {
	a.User = user
	a.require(auditUpdateRelationshipsFieldUser)
}

// SetAudit sets the Audit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuditUpdateRelationships) SetAudit(audit *RelationshipSingle) {
	a.Audit = audit
	a.require(auditUpdateRelationshipsFieldAudit)
}

func (a *AuditUpdateRelationships) UnmarshalJSON(data []byte) error {
	type unmarshaler AuditUpdateRelationships
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AuditUpdateRelationships(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AuditUpdateRelationships) MarshalJSON() ([]byte, error) {
	type embed AuditUpdateRelationships
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AuditUpdateRelationships) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	clawbackDataFieldID            = big.NewInt(1 << 0)
	clawbackDataFieldAttributes    = big.NewInt(1 << 1)
	clawbackDataFieldRelationships = big.NewInt(1 << 2)
)

type ClawbackData struct {
	// The internal ID of the notification
	ID            string                          `json:"id" url:"id"`
	Attributes    *FailedTransactionAttributes    `json:"attributes" url:"attributes"`
	Relationships *FailedTransactionRelationships `json:"relationships" url:"relationships"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ClawbackData) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ClawbackData) GetAttributes() *FailedTransactionAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

func (c *ClawbackData) GetRelationships() *FailedTransactionRelationships {
	if c == nil {
		return nil
	}
	return c.Relationships
}

func (c *ClawbackData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ClawbackData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClawbackData) SetID(id string) {
	c.ID = id
	c.require(clawbackDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClawbackData) SetAttributes(attributes *FailedTransactionAttributes) {
	c.Attributes = attributes
	c.require(clawbackDataFieldAttributes)
}

// SetRelationships sets the Relationships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ClawbackData) SetRelationships(relationships *FailedTransactionRelationships) {
	c.Relationships = relationships
	c.require(clawbackDataFieldRelationships)
}

func (c *ClawbackData) UnmarshalJSON(data []byte) error {
	type unmarshaler ClawbackData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ClawbackData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ClawbackData) MarshalJSON() ([]byte, error) {
	type embed ClawbackData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ClawbackData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	earnedRewardApprovedDataFieldID            = big.NewInt(1 << 0)
	earnedRewardApprovedDataFieldAttributes    = big.NewInt(1 << 1)
	earnedRewardApprovedDataFieldRelationships = big.NewInt(1 << 2)
)

type EarnedRewardApprovedData struct {
	// The internal ID of the notification
	ID            string                     `json:"id" url:"id"`
	Attributes    *EarnedRewardAttributes    `json:"attributes" url:"attributes"`
	Relationships *EarnedRewardRelationships `json:"relationships" url:"relationships"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EarnedRewardApprovedData) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EarnedRewardApprovedData) GetAttributes() *EarnedRewardAttributes {
	if e == nil {
		return nil
	}
	return e.Attributes
}

func (e *EarnedRewardApprovedData) GetRelationships() *EarnedRewardRelationships {
	if e == nil {
		return nil
	}
	return e.Relationships
}

func (e *EarnedRewardApprovedData) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EarnedRewardApprovedData) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardApprovedData) SetID(id string) {
	e.ID = id
	e.require(earnedRewardApprovedDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardApprovedData) SetAttributes(attributes *EarnedRewardAttributes) {
	e.Attributes = attributes
	e.require(earnedRewardApprovedDataFieldAttributes)
}

// SetRelationships sets the Relationships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardApprovedData) SetRelationships(relationships *EarnedRewardRelationships) {
	e.Relationships = relationships
	e.require(earnedRewardApprovedDataFieldRelationships)
}

func (e *EarnedRewardApprovedData) UnmarshalJSON(data []byte) error {
	type unmarshaler EarnedRewardApprovedData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EarnedRewardApprovedData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EarnedRewardApprovedData) MarshalJSON() ([]byte, error) {
	type embed EarnedRewardApprovedData
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EarnedRewardApprovedData) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	earnedRewardAttributesFieldMessage              = big.NewInt(1 << 0)
	earnedRewardAttributesFieldName                 = big.NewInt(1 << 1)
	earnedRewardAttributesFieldAttributionURL       = big.NewInt(1 << 2)
	earnedRewardAttributesFieldSurveyURL            = big.NewInt(1 << 3)
	earnedRewardAttributesFieldCardProductID        = big.NewInt(1 << 4)
	earnedRewardAttributesFieldTransactionTimestamp = big.NewInt(1 << 5)
)

type EarnedRewardAttributes struct {
	// The display message associated to the notification
	Message string `json:"message" url:"message"`
	// The name of the merchant
	Name string `json:"name" url:"name"`
	// The attribution URL to track user's interactions with the notification
	AttributionURL string `json:"attributionUrl" url:"attributionUrl"`
	// Post experience survey URL, if available. This will be present for rewards associated with local offers.
	SurveyURL *string `json:"surveyUrl,omitempty" url:"surveyUrl,omitempty"`
	// The ID of the card product
	CardProductID *string `json:"cardProductId,omitempty" url:"cardProductId,omitempty"`
	// The timestamp of the originating transaction in ISO format
	TransactionTimestamp *time.Time `json:"transactionTimestamp,omitempty" url:"transactionTimestamp,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EarnedRewardAttributes) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *EarnedRewardAttributes) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EarnedRewardAttributes) GetAttributionURL() string {
	if e == nil {
		return ""
	}
	return e.AttributionURL
}

func (e *EarnedRewardAttributes) GetSurveyURL() *string {
	if e == nil {
		return nil
	}
	return e.SurveyURL
}

func (e *EarnedRewardAttributes) GetCardProductID() *string {
	if e == nil {
		return nil
	}
	return e.CardProductID
}

func (e *EarnedRewardAttributes) GetTransactionTimestamp() *time.Time {
	if e == nil {
		return nil
	}
	return e.TransactionTimestamp
}

func (e *EarnedRewardAttributes) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EarnedRewardAttributes) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardAttributes) SetMessage(message string) {
	e.Message = message
	e.require(earnedRewardAttributesFieldMessage)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardAttributes) SetName(name string) {
	e.Name = name
	e.require(earnedRewardAttributesFieldName)
}

// SetAttributionURL sets the AttributionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardAttributes) SetAttributionURL(attributionURL string) {
	e.AttributionURL = attributionURL
	e.require(earnedRewardAttributesFieldAttributionURL)
}

// SetSurveyURL sets the SurveyURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardAttributes) SetSurveyURL(surveyURL *string) {
	e.SurveyURL = surveyURL
	e.require(earnedRewardAttributesFieldSurveyURL)
}

// SetCardProductID sets the CardProductID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardAttributes) SetCardProductID(cardProductID *string) {
	e.CardProductID = cardProductID
	e.require(earnedRewardAttributesFieldCardProductID)
}

// SetTransactionTimestamp sets the TransactionTimestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardAttributes) SetTransactionTimestamp(transactionTimestamp *time.Time) {
	e.TransactionTimestamp = transactionTimestamp
	e.require(earnedRewardAttributesFieldTransactionTimestamp)
}

func (e *EarnedRewardAttributes) UnmarshalJSON(data []byte) error {
	type embed EarnedRewardAttributes
	var unmarshaler = struct {
		embed
		TransactionTimestamp *internal.DateTime `json:"transactionTimestamp,omitempty"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EarnedRewardAttributes(unmarshaler.embed)
	e.TransactionTimestamp = unmarshaler.TransactionTimestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EarnedRewardAttributes) MarshalJSON() ([]byte, error) {
	type embed EarnedRewardAttributes
	var marshaler = struct {
		embed
		TransactionTimestamp *internal.DateTime `json:"transactionTimestamp,omitempty"`
	}{
		embed:                embed(*e),
		TransactionTimestamp: internal.NewOptionalDateTime(e.TransactionTimestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EarnedRewardAttributes) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	earnedRewardRelationshipsFieldUser        = big.NewInt(1 << 0)
	earnedRewardRelationshipsFieldTransaction = big.NewInt(1 << 1)
)

type EarnedRewardRelationships struct {
	User        *RelationshipSingle `json:"user" url:"user"`
	Transaction *RelationshipSingle `json:"transaction" url:"transaction"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EarnedRewardRelationships) GetUser() *RelationshipSingle {
	if e == nil {
		return nil
	}
	return e.User
}

func (e *EarnedRewardRelationships) GetTransaction() *RelationshipSingle {
	if e == nil {
		return nil
	}
	return e.Transaction
}

func (e *EarnedRewardRelationships) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EarnedRewardRelationships) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardRelationships) SetUser(user *RelationshipSingle) {
	e.User = user
	e.require(earnedRewardRelationshipsFieldUser)
}

// SetTransaction sets the Transaction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardRelationships) SetTransaction(transaction *RelationshipSingle) {
	e.Transaction = transaction
	e.require(earnedRewardRelationshipsFieldTransaction)
}

func (e *EarnedRewardRelationships) UnmarshalJSON(data []byte) error {
	type unmarshaler EarnedRewardRelationships
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EarnedRewardRelationships(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EarnedRewardRelationships) MarshalJSON() ([]byte, error) {
	type embed EarnedRewardRelationships
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EarnedRewardRelationships) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	earnedRewardSettledAttributesFieldMessage              = big.NewInt(1 << 0)
	earnedRewardSettledAttributesFieldName                 = big.NewInt(1 << 1)
	earnedRewardSettledAttributesFieldAttributionURL       = big.NewInt(1 << 2)
	earnedRewardSettledAttributesFieldSurveyURL            = big.NewInt(1 << 3)
	earnedRewardSettledAttributesFieldCardProductID        = big.NewInt(1 << 4)
	earnedRewardSettledAttributesFieldCommissionEarned     = big.NewInt(1 << 5)
	earnedRewardSettledAttributesFieldTransactionTimestamp = big.NewInt(1 << 6)
)

type EarnedRewardSettledAttributes struct {
	// The display message associated to the notification
	Message string `json:"message" url:"message"`
	// The name of the merchant
	Name string `json:"name" url:"name"`
	// The attribution URL to track user's interactions with the notification
	AttributionURL string `json:"attributionUrl" url:"attributionUrl"`
	// Post experience survey URL, if available. This will be present for rewards associated with local offers.
	SurveyURL *string `json:"surveyUrl,omitempty" url:"surveyUrl,omitempty"`
	// The ID of the card product
	CardProductID    *string          `json:"cardProductId,omitempty" url:"cardProductId,omitempty"`
	CommissionEarned *CommissionValue `json:"commissionEarned" url:"commissionEarned"`
	// The timestamp of the originating transaction in ISO format
	TransactionTimestamp *time.Time `json:"transactionTimestamp,omitempty" url:"transactionTimestamp,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EarnedRewardSettledAttributes) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

func (e *EarnedRewardSettledAttributes) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EarnedRewardSettledAttributes) GetAttributionURL() string {
	if e == nil {
		return ""
	}
	return e.AttributionURL
}

func (e *EarnedRewardSettledAttributes) GetSurveyURL() *string {
	if e == nil {
		return nil
	}
	return e.SurveyURL
}

func (e *EarnedRewardSettledAttributes) GetCardProductID() *string {
	if e == nil {
		return nil
	}
	return e.CardProductID
}

func (e *EarnedRewardSettledAttributes) GetCommissionEarned() *CommissionValue {
	if e == nil {
		return nil
	}
	return e.CommissionEarned
}

func (e *EarnedRewardSettledAttributes) GetTransactionTimestamp() *time.Time {
	if e == nil {
		return nil
	}
	return e.TransactionTimestamp
}

func (e *EarnedRewardSettledAttributes) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EarnedRewardSettledAttributes) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetMessage(message string) {
	e.Message = message
	e.require(earnedRewardSettledAttributesFieldMessage)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetName(name string) {
	e.Name = name
	e.require(earnedRewardSettledAttributesFieldName)
}

// SetAttributionURL sets the AttributionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetAttributionURL(attributionURL string) {
	e.AttributionURL = attributionURL
	e.require(earnedRewardSettledAttributesFieldAttributionURL)
}

// SetSurveyURL sets the SurveyURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetSurveyURL(surveyURL *string) {
	e.SurveyURL = surveyURL
	e.require(earnedRewardSettledAttributesFieldSurveyURL)
}

// SetCardProductID sets the CardProductID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetCardProductID(cardProductID *string) {
	e.CardProductID = cardProductID
	e.require(earnedRewardSettledAttributesFieldCardProductID)
}

// SetCommissionEarned sets the CommissionEarned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetCommissionEarned(commissionEarned *CommissionValue) {
	e.CommissionEarned = commissionEarned
	e.require(earnedRewardSettledAttributesFieldCommissionEarned)
}

// SetTransactionTimestamp sets the TransactionTimestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledAttributes) SetTransactionTimestamp(transactionTimestamp *time.Time) {
	e.TransactionTimestamp = transactionTimestamp
	e.require(earnedRewardSettledAttributesFieldTransactionTimestamp)
}

func (e *EarnedRewardSettledAttributes) UnmarshalJSON(data []byte) error {
	type embed EarnedRewardSettledAttributes
	var unmarshaler = struct {
		embed
		TransactionTimestamp *internal.DateTime `json:"transactionTimestamp,omitempty"`
	}{
		embed: embed(*e),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*e = EarnedRewardSettledAttributes(unmarshaler.embed)
	e.TransactionTimestamp = unmarshaler.TransactionTimestamp.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EarnedRewardSettledAttributes) MarshalJSON() ([]byte, error) {
	type embed EarnedRewardSettledAttributes
	var marshaler = struct {
		embed
		TransactionTimestamp *internal.DateTime `json:"transactionTimestamp,omitempty"`
	}{
		embed:                embed(*e),
		TransactionTimestamp: internal.NewOptionalDateTime(e.TransactionTimestamp),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EarnedRewardSettledAttributes) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	earnedRewardSettledDataFieldID            = big.NewInt(1 << 0)
	earnedRewardSettledDataFieldAttributes    = big.NewInt(1 << 1)
	earnedRewardSettledDataFieldRelationships = big.NewInt(1 << 2)
)

type EarnedRewardSettledData struct {
	// The internal ID of the notification
	ID            string                         `json:"id" url:"id"`
	Attributes    *EarnedRewardSettledAttributes `json:"attributes" url:"attributes"`
	Relationships *EarnedRewardRelationships     `json:"relationships" url:"relationships"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EarnedRewardSettledData) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EarnedRewardSettledData) GetAttributes() *EarnedRewardSettledAttributes {
	if e == nil {
		return nil
	}
	return e.Attributes
}

func (e *EarnedRewardSettledData) GetRelationships() *EarnedRewardRelationships {
	if e == nil {
		return nil
	}
	return e.Relationships
}

func (e *EarnedRewardSettledData) GetExtraProperties() map[string]interface{} {
	if e == nil {
		return nil
	}
	return e.extraProperties
}

func (e *EarnedRewardSettledData) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledData) SetID(id string) {
	e.ID = id
	e.require(earnedRewardSettledDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledData) SetAttributes(attributes *EarnedRewardSettledAttributes) {
	e.Attributes = attributes
	e.require(earnedRewardSettledDataFieldAttributes)
}

// SetRelationships sets the Relationships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *EarnedRewardSettledData) SetRelationships(relationships *EarnedRewardRelationships) {
	e.Relationships = relationships
	e.require(earnedRewardSettledDataFieldRelationships)
}

func (e *EarnedRewardSettledData) UnmarshalJSON(data []byte) error {
	type unmarshaler EarnedRewardSettledData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EarnedRewardSettledData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EarnedRewardSettledData) MarshalJSON() ([]byte, error) {
	type embed EarnedRewardSettledData
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *EarnedRewardSettledData) String() string {
	if e == nil {
		return "<nil>"
	}
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	failedTransactionAttributesFieldMessage       = big.NewInt(1 << 0)
	failedTransactionAttributesFieldReason        = big.NewInt(1 << 1)
	failedTransactionAttributesFieldName          = big.NewInt(1 << 2)
	failedTransactionAttributesFieldCardProductID = big.NewInt(1 << 3)
)

type FailedTransactionAttributes struct {
	// The display message associated to the notification
	Message string `json:"message" url:"message"`
	// The reason for the transaction failure
	Reason string `json:"reason" url:"reason"`
	// The name of the merchant
	Name string `json:"name" url:"name"`
	// The ID of the card product
	CardProductID *string `json:"cardProductId,omitempty" url:"cardProductId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FailedTransactionAttributes) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}

func (f *FailedTransactionAttributes) GetReason() string {
	if f == nil {
		return ""
	}
	return f.Reason
}

func (f *FailedTransactionAttributes) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FailedTransactionAttributes) GetCardProductID() *string {
	if f == nil {
		return nil
	}
	return f.CardProductID
}

func (f *FailedTransactionAttributes) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FailedTransactionAttributes) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionAttributes) SetMessage(message string) {
	f.Message = message
	f.require(failedTransactionAttributesFieldMessage)
}

// SetReason sets the Reason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionAttributes) SetReason(reason string) {
	f.Reason = reason
	f.require(failedTransactionAttributesFieldReason)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionAttributes) SetName(name string) {
	f.Name = name
	f.require(failedTransactionAttributesFieldName)
}

// SetCardProductID sets the CardProductID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionAttributes) SetCardProductID(cardProductID *string) {
	f.CardProductID = cardProductID
	f.require(failedTransactionAttributesFieldCardProductID)
}

func (f *FailedTransactionAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler FailedTransactionAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FailedTransactionAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FailedTransactionAttributes) MarshalJSON() ([]byte, error) {
	type embed FailedTransactionAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FailedTransactionAttributes) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	failedTransactionDataFieldID            = big.NewInt(1 << 0)
	failedTransactionDataFieldAttributes    = big.NewInt(1 << 1)
	failedTransactionDataFieldRelationships = big.NewInt(1 << 2)
)

type FailedTransactionData struct {
	// The internal ID of the notification
	ID            string                          `json:"id" url:"id"`
	Attributes    *FailedTransactionAttributes    `json:"attributes" url:"attributes"`
	Relationships *FailedTransactionRelationships `json:"relationships" url:"relationships"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FailedTransactionData) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FailedTransactionData) GetAttributes() *FailedTransactionAttributes {
	if f == nil {
		return nil
	}
	return f.Attributes
}

func (f *FailedTransactionData) GetRelationships() *FailedTransactionRelationships {
	if f == nil {
		return nil
	}
	return f.Relationships
}

func (f *FailedTransactionData) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FailedTransactionData) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionData) SetID(id string) {
	f.ID = id
	f.require(failedTransactionDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionData) SetAttributes(attributes *FailedTransactionAttributes) {
	f.Attributes = attributes
	f.require(failedTransactionDataFieldAttributes)
}

// SetRelationships sets the Relationships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionData) SetRelationships(relationships *FailedTransactionRelationships) {
	f.Relationships = relationships
	f.require(failedTransactionDataFieldRelationships)
}

func (f *FailedTransactionData) UnmarshalJSON(data []byte) error {
	type unmarshaler FailedTransactionData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FailedTransactionData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FailedTransactionData) MarshalJSON() ([]byte, error) {
	type embed FailedTransactionData
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FailedTransactionData) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	failedTransactionRelationshipsFieldUser        = big.NewInt(1 << 0)
	failedTransactionRelationshipsFieldOffer       = big.NewInt(1 << 1)
	failedTransactionRelationshipsFieldTransaction = big.NewInt(1 << 2)
)

type FailedTransactionRelationships struct {
	User        *RelationshipSingle `json:"user" url:"user"`
	Offer       *RelationshipSingle `json:"offer" url:"offer"`
	Transaction *RelationshipSingle `json:"transaction" url:"transaction"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FailedTransactionRelationships) GetUser() *RelationshipSingle {
	if f == nil {
		return nil
	}
	return f.User
}

func (f *FailedTransactionRelationships) GetOffer() *RelationshipSingle {
	if f == nil {
		return nil
	}
	return f.Offer
}

func (f *FailedTransactionRelationships) GetTransaction() *RelationshipSingle {
	if f == nil {
		return nil
	}
	return f.Transaction
}

func (f *FailedTransactionRelationships) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FailedTransactionRelationships) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionRelationships) SetUser(user *RelationshipSingle) {
	f.User = user
	f.require(failedTransactionRelationshipsFieldUser)
}

// SetOffer sets the Offer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionRelationships) SetOffer(offer *RelationshipSingle) {
	f.Offer = offer
	f.require(failedTransactionRelationshipsFieldOffer)
}

// SetTransaction sets the Transaction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedTransactionRelationships) SetTransaction(transaction *RelationshipSingle) {
	f.Transaction = transaction
	f.require(failedTransactionRelationshipsFieldTransaction)
}

func (f *FailedTransactionRelationships) UnmarshalJSON(data []byte) error {
	type unmarshaler FailedTransactionRelationships
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FailedTransactionRelationships(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FailedTransactionRelationships) MarshalJSON() ([]byte, error) {
	type embed FailedTransactionRelationships
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FailedTransactionRelationships) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fileResultDataFieldID         = big.NewInt(1 << 0)
	fileResultDataFieldAttributes = big.NewInt(1 << 1)
)

type FileResultData struct {
	// The internal ID of the notification
	ID         string                 `json:"id" url:"id"`
	Attributes *FileMetadataAttribute `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FileResultData) GetID() string {
	if f == nil {
		return ""
	}
	return f.ID
}

func (f *FileResultData) GetAttributes() *FileMetadataAttribute {
	if f == nil {
		return nil
	}
	return f.Attributes
}

func (f *FileResultData) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FileResultData) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileResultData) SetID(id string) {
	f.ID = id
	f.require(fileResultDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FileResultData) SetAttributes(attributes *FileMetadataAttribute) {
	f.Attributes = attributes
	f.require(fileResultDataFieldAttributes)
}

func (f *FileResultData) UnmarshalJSON(data []byte) error {
	type unmarshaler FileResultData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FileResultData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FileResultData) MarshalJSON() ([]byte, error) {
	type embed FileResultData
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FileResultData) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type NotificationDataUnion struct {
	Type                 string
	EarnedRewardApproved *EarnedRewardApprovedData
	EarnedRewardSettled  *EarnedRewardSettledData
	ValidTransaction     *ValidTransactionData
	FailedTransaction    *FailedTransactionData
	Clawback             *ClawbackData
	AuditUpdate          *AuditUpdateData
	FileProcessingResult *FileResultData
}

func (n *NotificationDataUnion) GetType() string {
	if n == nil {
		return ""
	}
	return n.Type
}

func (n *NotificationDataUnion) GetEarnedRewardApproved() *EarnedRewardApprovedData {
	if n == nil {
		return nil
	}
	return n.EarnedRewardApproved
}

func (n *NotificationDataUnion) GetEarnedRewardSettled() *EarnedRewardSettledData {
	if n == nil {
		return nil
	}
	return n.EarnedRewardSettled
}

func (n *NotificationDataUnion) GetValidTransaction() *ValidTransactionData {
	if n == nil {
		return nil
	}
	return n.ValidTransaction
}

func (n *NotificationDataUnion) GetFailedTransaction() *FailedTransactionData {
	if n == nil {
		return nil
	}
	return n.FailedTransaction
}

func (n *NotificationDataUnion) GetClawback() *ClawbackData {
	if n == nil {
		return nil
	}
	return n.Clawback
}

func (n *NotificationDataUnion) GetAuditUpdate() *AuditUpdateData {
	if n == nil {
		return nil
	}
	return n.AuditUpdate
}

func (n *NotificationDataUnion) GetFileProcessingResult() *FileResultData {
	if n == nil {
		return nil
	}
	return n.FileProcessingResult
}

func (n *NotificationDataUnion) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	n.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", n)
	}
	switch unmarshaler.Type {
	case "earnedRewardApproved":
		value := new(EarnedRewardApprovedData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.EarnedRewardApproved = value
	case "earnedRewardSettled":
		value := new(EarnedRewardSettledData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.EarnedRewardSettled = value
	case "validTransaction":
		value := new(ValidTransactionData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.ValidTransaction = value
	case "failedTransaction":
		value := new(FailedTransactionData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.FailedTransaction = value
	case "clawback":
		value := new(ClawbackData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.Clawback = value
	case "auditUpdate":
		value := new(AuditUpdateData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.AuditUpdate = value
	case "fileProcessingResult":
		value := new(FileResultData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.FileProcessingResult = value
	}
	return nil
}

func (n NotificationDataUnion) MarshalJSON() ([]byte, error) {
	if err := n.validate(); err != nil {
		return nil, err
	}
	if n.EarnedRewardApproved != nil {
		return internal.MarshalJSONWithExtraProperty(n.EarnedRewardApproved, "type", "earnedRewardApproved")
	}
	if n.EarnedRewardSettled != nil {
		return internal.MarshalJSONWithExtraProperty(n.EarnedRewardSettled, "type", "earnedRewardSettled")
	}
	if n.ValidTransaction != nil {
		return internal.MarshalJSONWithExtraProperty(n.ValidTransaction, "type", "validTransaction")
	}
	if n.FailedTransaction != nil {
		return internal.MarshalJSONWithExtraProperty(n.FailedTransaction, "type", "failedTransaction")
	}
	if n.Clawback != nil {
		return internal.MarshalJSONWithExtraProperty(n.Clawback, "type", "clawback")
	}
	if n.AuditUpdate != nil {
		return internal.MarshalJSONWithExtraProperty(n.AuditUpdate, "type", "auditUpdate")
	}
	if n.FileProcessingResult != nil {
		return internal.MarshalJSONWithExtraProperty(n.FileProcessingResult, "type", "fileProcessingResult")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", n)
}

type NotificationDataUnionVisitor interface {
	VisitEarnedRewardApproved(*EarnedRewardApprovedData) error
	VisitEarnedRewardSettled(*EarnedRewardSettledData) error
	VisitValidTransaction(*ValidTransactionData) error
	VisitFailedTransaction(*FailedTransactionData) error
	VisitClawback(*ClawbackData) error
	VisitAuditUpdate(*AuditUpdateData) error
	VisitFileProcessingResult(*FileResultData) error
}

func (n *NotificationDataUnion) Accept(visitor NotificationDataUnionVisitor) error {
	if n.EarnedRewardApproved != nil {
		return visitor.VisitEarnedRewardApproved(n.EarnedRewardApproved)
	}
	if n.EarnedRewardSettled != nil {
		return visitor.VisitEarnedRewardSettled(n.EarnedRewardSettled)
	}
	if n.ValidTransaction != nil {
		return visitor.VisitValidTransaction(n.ValidTransaction)
	}
	if n.FailedTransaction != nil {
		return visitor.VisitFailedTransaction(n.FailedTransaction)
	}
	if n.Clawback != nil {
		return visitor.VisitClawback(n.Clawback)
	}
	if n.AuditUpdate != nil {
		return visitor.VisitAuditUpdate(n.AuditUpdate)
	}
	if n.FileProcessingResult != nil {
		return visitor.VisitFileProcessingResult(n.FileProcessingResult)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", n)
}

func (n *NotificationDataUnion) validate() error {
	if n == nil {
		return fmt.Errorf("type %T is nil", n)
	}
	var fields []string
	if n.EarnedRewardApproved != nil {
		fields = append(fields, "earnedRewardApproved")
	}
	if n.EarnedRewardSettled != nil {
		fields = append(fields, "earnedRewardSettled")
	}
	if n.ValidTransaction != nil {
		fields = append(fields, "validTransaction")
	}
	if n.FailedTransaction != nil {
		fields = append(fields, "failedTransaction")
	}
	if n.Clawback != nil {
		fields = append(fields, "clawback")
	}
	if n.AuditUpdate != nil {
		fields = append(fields, "auditUpdate")
	}
	if n.FileProcessingResult != nil {
		fields = append(fields, "fileProcessingResult")
	}
	if len(fields) == 0 {
		if n.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", n, n.Type)
		}
		return fmt.Errorf("type %T is empty", n)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", n, fields)
	}
	if n.Type != "" {
		field := fields[0]
		if n.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				n,
				n.Type,
				n,
			)
		}
	}
	return nil
}

var (
	notificationMetadataFieldIssuerID   = big.NewInt(1 << 0)
	notificationMetadataFieldIssuerName = big.NewInt(1 << 1)
)

type NotificationMetadata struct {
	IssuerID   string `json:"issuerId" url:"issuerId"`
	IssuerName string `json:"issuerName" url:"issuerName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationMetadata) GetIssuerID() string {
	if n == nil {
		return ""
	}
	return n.IssuerID
}

func (n *NotificationMetadata) GetIssuerName() string {
	if n == nil {
		return ""
	}
	return n.IssuerName
}

func (n *NotificationMetadata) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NotificationMetadata) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetIssuerID sets the IssuerID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationMetadata) SetIssuerID(issuerID string) {
	n.IssuerID = issuerID
	n.require(notificationMetadataFieldIssuerID)
}

// SetIssuerName sets the IssuerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationMetadata) SetIssuerName(issuerName string) {
	n.IssuerName = issuerName
	n.require(notificationMetadataFieldIssuerName)
}

func (n *NotificationMetadata) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationMetadata
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationMetadata(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationMetadata) MarshalJSON() ([]byte, error) {
	type embed NotificationMetadata
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationMetadata) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	notificationPayloadFieldData   = big.NewInt(1 << 0)
	notificationPayloadFieldMeta   = big.NewInt(1 << 1)
	notificationPayloadFieldErrors = big.NewInt(1 << 2)
)

type NotificationPayload struct {
	Data   *NotificationDataUnion `json:"data" url:"data"`
	Meta   *NotificationMetadata  `json:"meta,omitempty" url:"meta,omitempty"`
	Errors []*ErrorObject         `json:"errors,omitempty" url:"errors,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NotificationPayload) GetData() *NotificationDataUnion {
	if n == nil {
		return nil
	}
	return n.Data
}

func (n *NotificationPayload) GetMeta() *NotificationMetadata {
	if n == nil {
		return nil
	}
	return n.Meta
}

func (n *NotificationPayload) GetErrors() []*ErrorObject {
	if n == nil {
		return nil
	}
	return n.Errors
}

func (n *NotificationPayload) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NotificationPayload) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationPayload) SetData(data *NotificationDataUnion) {
	n.Data = data
	n.require(notificationPayloadFieldData)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationPayload) SetMeta(meta *NotificationMetadata) {
	n.Meta = meta
	n.require(notificationPayloadFieldMeta)
}

// SetErrors sets the Errors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NotificationPayload) SetErrors(errors []*ErrorObject) {
	n.Errors = errors
	n.require(notificationPayloadFieldErrors)
}

func (n *NotificationPayload) UnmarshalJSON(data []byte) error {
	type unmarshaler NotificationPayload
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NotificationPayload(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NotificationPayload) MarshalJSON() ([]byte, error) {
	type embed NotificationPayload
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NotificationPayload) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	rewardNotificationAttributesFieldMessage        = big.NewInt(1 << 0)
	rewardNotificationAttributesFieldName           = big.NewInt(1 << 1)
	rewardNotificationAttributesFieldAttributionURL = big.NewInt(1 << 2)
	rewardNotificationAttributesFieldSurveyURL      = big.NewInt(1 << 3)
	rewardNotificationAttributesFieldCardProductID  = big.NewInt(1 << 4)
)

type RewardNotificationAttributes struct {
	// The display message associated to the notification
	Message string `json:"message" url:"message"`
	// The name of the merchant
	Name string `json:"name" url:"name"`
	// The attribution URL to track user's interactions with the notification
	AttributionURL string `json:"attributionUrl" url:"attributionUrl"`
	// Post experience survey URL, if available. This will be present for rewards associated with local offers.
	SurveyURL *string `json:"surveyUrl,omitempty" url:"surveyUrl,omitempty"`
	// The ID of the card product
	CardProductID *string `json:"cardProductId,omitempty" url:"cardProductId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RewardNotificationAttributes) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RewardNotificationAttributes) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RewardNotificationAttributes) GetAttributionURL() string {
	if r == nil {
		return ""
	}
	return r.AttributionURL
}

func (r *RewardNotificationAttributes) GetSurveyURL() *string {
	if r == nil {
		return nil
	}
	return r.SurveyURL
}

func (r *RewardNotificationAttributes) GetCardProductID() *string {
	if r == nil {
		return nil
	}
	return r.CardProductID
}

func (r *RewardNotificationAttributes) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RewardNotificationAttributes) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RewardNotificationAttributes) SetMessage(message string) {
	r.Message = message
	r.require(rewardNotificationAttributesFieldMessage)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RewardNotificationAttributes) SetName(name string) {
	r.Name = name
	r.require(rewardNotificationAttributesFieldName)
}

// SetAttributionURL sets the AttributionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RewardNotificationAttributes) SetAttributionURL(attributionURL string) {
	r.AttributionURL = attributionURL
	r.require(rewardNotificationAttributesFieldAttributionURL)
}

// SetSurveyURL sets the SurveyURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RewardNotificationAttributes) SetSurveyURL(surveyURL *string) {
	r.SurveyURL = surveyURL
	r.require(rewardNotificationAttributesFieldSurveyURL)
}

// SetCardProductID sets the CardProductID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RewardNotificationAttributes) SetCardProductID(cardProductID *string) {
	r.CardProductID = cardProductID
	r.require(rewardNotificationAttributesFieldCardProductID)
}

func (r *RewardNotificationAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler RewardNotificationAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RewardNotificationAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RewardNotificationAttributes) MarshalJSON() ([]byte, error) {
	type embed RewardNotificationAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RewardNotificationAttributes) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	transactionRelationshipsFieldUser        = big.NewInt(1 << 0)
	transactionRelationshipsFieldOffer       = big.NewInt(1 << 1)
	transactionRelationshipsFieldTransaction = big.NewInt(1 << 2)
)

type TransactionRelationships struct {
	User        *RelationshipSingle `json:"user" url:"user"`
	Offer       *RelationshipSingle `json:"offer" url:"offer"`
	Transaction *RelationshipSingle `json:"transaction" url:"transaction"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TransactionRelationships) GetUser() *RelationshipSingle {
	if t == nil {
		return nil
	}
	return t.User
}

func (t *TransactionRelationships) GetOffer() *RelationshipSingle {
	if t == nil {
		return nil
	}
	return t.Offer
}

func (t *TransactionRelationships) GetTransaction() *RelationshipSingle {
	if t == nil {
		return nil
	}
	return t.Transaction
}

func (t *TransactionRelationships) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TransactionRelationships) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionRelationships) SetUser(user *RelationshipSingle) {
	t.User = user
	t.require(transactionRelationshipsFieldUser)
}

// SetOffer sets the Offer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionRelationships) SetOffer(offer *RelationshipSingle) {
	t.Offer = offer
	t.require(transactionRelationshipsFieldOffer)
}

// SetTransaction sets the Transaction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TransactionRelationships) SetTransaction(transaction *RelationshipSingle) {
	t.Transaction = transaction
	t.require(transactionRelationshipsFieldTransaction)
}

func (t *TransactionRelationships) UnmarshalJSON(data []byte) error {
	type unmarshaler TransactionRelationships
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TransactionRelationships(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TransactionRelationships) MarshalJSON() ([]byte, error) {
	type embed TransactionRelationships
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TransactionRelationships) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

var (
	validTransactionAttributesFieldMessage          = big.NewInt(1 << 0)
	validTransactionAttributesFieldName             = big.NewInt(1 << 1)
	validTransactionAttributesFieldAttributionURL   = big.NewInt(1 << 2)
	validTransactionAttributesFieldSurveyURL        = big.NewInt(1 << 3)
	validTransactionAttributesFieldCardProductID    = big.NewInt(1 << 4)
	validTransactionAttributesFieldCommissionEarned = big.NewInt(1 << 5)
)

type ValidTransactionAttributes struct {
	// The display message associated to the notification
	Message string `json:"message" url:"message"`
	// The name of the merchant
	Name string `json:"name" url:"name"`
	// The attribution URL to track user's interactions with the notification
	AttributionURL string `json:"attributionUrl" url:"attributionUrl"`
	// Post experience survey URL, if available. This will be present for rewards associated with local offers.
	SurveyURL *string `json:"surveyUrl,omitempty" url:"surveyUrl,omitempty"`
	// The ID of the card product
	CardProductID    *string                           `json:"cardProductId,omitempty" url:"cardProductId,omitempty"`
	CommissionEarned *ValidTransactionCommissionEarned `json:"commissionEarned" url:"commissionEarned"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ValidTransactionAttributes) GetMessage() string {
	if v == nil {
		return ""
	}
	return v.Message
}

func (v *ValidTransactionAttributes) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *ValidTransactionAttributes) GetAttributionURL() string {
	if v == nil {
		return ""
	}
	return v.AttributionURL
}

func (v *ValidTransactionAttributes) GetSurveyURL() *string {
	if v == nil {
		return nil
	}
	return v.SurveyURL
}

func (v *ValidTransactionAttributes) GetCardProductID() *string {
	if v == nil {
		return nil
	}
	return v.CardProductID
}

func (v *ValidTransactionAttributes) GetCommissionEarned() *ValidTransactionCommissionEarned {
	if v == nil {
		return nil
	}
	return v.CommissionEarned
}

func (v *ValidTransactionAttributes) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *ValidTransactionAttributes) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionAttributes) SetMessage(message string) {
	v.Message = message
	v.require(validTransactionAttributesFieldMessage)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionAttributes) SetName(name string) {
	v.Name = name
	v.require(validTransactionAttributesFieldName)
}

// SetAttributionURL sets the AttributionURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionAttributes) SetAttributionURL(attributionURL string) {
	v.AttributionURL = attributionURL
	v.require(validTransactionAttributesFieldAttributionURL)
}

// SetSurveyURL sets the SurveyURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionAttributes) SetSurveyURL(surveyURL *string) {
	v.SurveyURL = surveyURL
	v.require(validTransactionAttributesFieldSurveyURL)
}

// SetCardProductID sets the CardProductID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionAttributes) SetCardProductID(cardProductID *string) {
	v.CardProductID = cardProductID
	v.require(validTransactionAttributesFieldCardProductID)
}

// SetCommissionEarned sets the CommissionEarned field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionAttributes) SetCommissionEarned(commissionEarned *ValidTransactionCommissionEarned) {
	v.CommissionEarned = commissionEarned
	v.require(validTransactionAttributesFieldCommissionEarned)
}

func (v *ValidTransactionAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidTransactionAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidTransactionAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidTransactionAttributes) MarshalJSON() ([]byte, error) {
	type embed ValidTransactionAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *ValidTransactionAttributes) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	validTransactionCommissionEarnedFieldIssuer = big.NewInt(1 << 0)
	validTransactionCommissionEarnedFieldUser   = big.NewInt(1 << 1)
)

type ValidTransactionCommissionEarned struct {
	Issuer *CommissionValue `json:"issuer" url:"issuer"`
	User   *CommissionValue `json:"user" url:"user"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ValidTransactionCommissionEarned) GetIssuer() *CommissionValue {
	if v == nil {
		return nil
	}
	return v.Issuer
}

func (v *ValidTransactionCommissionEarned) GetUser() *CommissionValue {
	if v == nil {
		return nil
	}
	return v.User
}

func (v *ValidTransactionCommissionEarned) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *ValidTransactionCommissionEarned) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetIssuer sets the Issuer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionCommissionEarned) SetIssuer(issuer *CommissionValue) {
	v.Issuer = issuer
	v.require(validTransactionCommissionEarnedFieldIssuer)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionCommissionEarned) SetUser(user *CommissionValue) {
	v.User = user
	v.require(validTransactionCommissionEarnedFieldUser)
}

func (v *ValidTransactionCommissionEarned) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidTransactionCommissionEarned
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidTransactionCommissionEarned(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidTransactionCommissionEarned) MarshalJSON() ([]byte, error) {
	type embed ValidTransactionCommissionEarned
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *ValidTransactionCommissionEarned) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}

var (
	validTransactionDataFieldID            = big.NewInt(1 << 0)
	validTransactionDataFieldAttributes    = big.NewInt(1 << 1)
	validTransactionDataFieldRelationships = big.NewInt(1 << 2)
)

type ValidTransactionData struct {
	// The internal ID of the notification
	ID            string                      `json:"id" url:"id"`
	Attributes    *ValidTransactionAttributes `json:"attributes" url:"attributes"`
	Relationships *TransactionRelationships   `json:"relationships" url:"relationships"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *ValidTransactionData) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *ValidTransactionData) GetAttributes() *ValidTransactionAttributes {
	if v == nil {
		return nil
	}
	return v.Attributes
}

func (v *ValidTransactionData) GetRelationships() *TransactionRelationships {
	if v == nil {
		return nil
	}
	return v.Relationships
}

func (v *ValidTransactionData) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *ValidTransactionData) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionData) SetID(id string) {
	v.ID = id
	v.require(validTransactionDataFieldID)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionData) SetAttributes(attributes *ValidTransactionAttributes) {
	v.Attributes = attributes
	v.require(validTransactionDataFieldAttributes)
}

// SetRelationships sets the Relationships field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *ValidTransactionData) SetRelationships(relationships *TransactionRelationships) {
	v.Relationships = relationships
	v.require(validTransactionDataFieldRelationships)
}

func (v *ValidTransactionData) UnmarshalJSON(data []byte) error {
	type unmarshaler ValidTransactionData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = ValidTransactionData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *ValidTransactionData) MarshalJSON() ([]byte, error) {
	type embed ValidTransactionData
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *ValidTransactionData) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
