// Code generated by Fern. DO NOT EDIT.

package kard

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/KardFinancial/kard-go-sdk/v3/internal"
	big "math/big"
)

// Error response indicating that the network is blocked.
var (
	networkBlockedErrorBodyFieldMessage = big.NewInt(1 << 0)
)

type NetworkBlockedErrorBody struct {
	// A message indicating that the network is blocked.
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NetworkBlockedErrorBody) GetMessage() string {
	if n == nil {
		return ""
	}
	return n.Message
}

func (n *NetworkBlockedErrorBody) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NetworkBlockedErrorBody) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NetworkBlockedErrorBody) SetMessage(message string) {
	n.Message = message
	n.require(networkBlockedErrorBodyFieldMessage)
}

func (n *NetworkBlockedErrorBody) UnmarshalJSON(data []byte) error {
	type unmarshaler NetworkBlockedErrorBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NetworkBlockedErrorBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NetworkBlockedErrorBody) MarshalJSON() ([]byte, error) {
	type embed NetworkBlockedErrorBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NetworkBlockedErrorBody) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Response indicating the status of the ping.
var (
	pingResponseObjectFieldMessage   = big.NewInt(1 << 0)
	pingResponseObjectFieldStatus    = big.NewInt(1 << 1)
	pingResponseObjectFieldTimestamp = big.NewInt(1 << 2)
)

type PingResponseObject struct {
	// A message indicating the status of the ping.
	Message string `json:"message" url:"message"`
	// The status of the ping.
	Status string `json:"status" url:"status"`
	// The timestamp of the ping.
	Timestamp string `json:"timestamp" url:"timestamp"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PingResponseObject) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

func (p *PingResponseObject) GetStatus() string {
	if p == nil {
		return ""
	}
	return p.Status
}

func (p *PingResponseObject) GetTimestamp() string {
	if p == nil {
		return ""
	}
	return p.Timestamp
}

func (p *PingResponseObject) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PingResponseObject) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PingResponseObject) SetMessage(message string) {
	p.Message = message
	p.require(pingResponseObjectFieldMessage)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PingResponseObject) SetStatus(status string) {
	p.Status = status
	p.require(pingResponseObjectFieldStatus)
}

// SetTimestamp sets the Timestamp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PingResponseObject) SetTimestamp(timestamp string) {
	p.Timestamp = timestamp
	p.require(pingResponseObjectFieldTimestamp)
}

func (p *PingResponseObject) UnmarshalJSON(data []byte) error {
	type unmarshaler PingResponseObject
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PingResponseObject(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PingResponseObject) MarshalJSON() ([]byte, error) {
	type embed PingResponseObject
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PingResponseObject) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
