// Code generated by Fern. DO NOT EDIT.

package attributions

import (
	context "context"
	os "os"

	kardgosdk "github.com/KardFinancial/kard-go-sdk"
	core "github.com/KardFinancial/kard-go-sdk/core"
	internal "github.com/KardFinancial/kard-go-sdk/internal"
	option "github.com/KardFinancial/kard-go-sdk/option"
	users "github.com/KardFinancial/kard-go-sdk/users"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.ClientID == "" {
		options.ClientID = os.Getenv("KARD_CLIENT_ID")
	}
	if options.ClientSecret == "" {
		options.ClientSecret = os.Getenv("KARD_CLIENT_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Call this endpoint to send attribution events made by a single enrolled user for processing. A maximum of 100 events can be included in a single request.
//
// <b>Required scopes:</b> `attributions:write`
func (c *Client) Create(
	ctx context.Context,
	organizationID kardgosdk.OrganizationID,
	userID kardgosdk.UserID,
	request *users.CreateAttributionRequestObject,
	opts ...option.RequestOption,
) (*users.CreateAttributionResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		organizationID,
		userID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Record when a user activates an offer. Creates an attribution event with eventCode=ACTIVATE and medium=CTA.
// Optionally include the offer data by passing `include=offer`.
func (c *Client) Activate(
	ctx context.Context,
	organizationID kardgosdk.OrganizationID,
	userID kardgosdk.UserID,
	// The unique identifier of the offer being activated
	offerID string,
	request *users.ActivateOfferRequest,
	opts ...option.RequestOption,
) (*users.ActivateOfferResponse, error) {
	response, err := c.WithRawResponse.Activate(
		ctx,
		organizationID,
		userID,
		offerID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Record when a user boosts an offer. Creates an attribution event with eventCode=BOOST and medium=CTA.
// Optionally include the offer data by passing `include=offer`.
func (c *Client) Boost(
	ctx context.Context,
	organizationID kardgosdk.OrganizationID,
	userID kardgosdk.UserID,
	// The unique identifier of the offer being boosted
	offerID string,
	request *users.BoostOfferRequest,
	opts ...option.RequestOption,
) (*users.BoostOfferResponse, error) {
	response, err := c.WithRawResponse.Boost(
		ctx,
		organizationID,
		userID,
		offerID,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
