// Code generated by Fern. DO NOT EDIT.

package attributions

import (
	context "context"
	http "net/http"

	kard "github.com/KardFinancial/kard-go-sdk/v12"
	core "github.com/KardFinancial/kard-go-sdk/v12/core"
	internal "github.com/KardFinancial/kard-go-sdk/v12/internal"
	option "github.com/KardFinancial/kard-go-sdk/v12/option"
	users "github.com/KardFinancial/kard-go-sdk/v12/users"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) Create(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	request *users.CreateAttributionRequestObject,
	opts ...option.RequestOption,
) (*core.Response[*users.CreateAttributionResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/users/%v/attributions",
		organizationId,
		userId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *users.CreateAttributionResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(users.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*users.CreateAttributionResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Activate(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	// The unique identifier of the offer being activated
	offerId string,
	request *users.ActivateOfferRequest,
	opts ...option.RequestOption,
) (*core.Response[*users.ActivateOfferResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/users/%v/offers/%v/activate",
		organizationId,
		userId,
		offerId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *users.ActivateOfferResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(users.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*users.ActivateOfferResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Boost(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	// The unique identifier of the offer being boosted
	offerId string,
	request *users.BoostOfferRequest,
	opts ...option.RequestOption,
) (*core.Response[*users.BoostOfferResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/users/%v/offers/%v/boost",
		organizationId,
		userId,
		offerId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *users.BoostOfferResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(users.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*users.BoostOfferResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ActivatePlacementSlot(
	ctx context.Context,
	organizationId kard.OrganizationId,
	userId kard.UserId,
	// Unique identifier of the placement (UUID v7)
	placementId string,
	// Stable identifier for the slot within the placement
	slotId string,
	opts ...option.RequestOption,
) (*core.Response[*users.ActivatePlacementSlotResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/users/%v/placements/%v/slot/%v/activate",
		organizationId,
		userId,
		placementId,
		slotId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *users.ActivatePlacementSlotResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(users.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*users.ActivatePlacementSlotResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
