// Code generated by Fern. DO NOT EDIT.

package ping

import (
	context "context"
	os "os"

	kardgosdk "github.com/KardFinancial/kard-go-sdk"
	core "github.com/KardFinancial/kard-go-sdk/core"
	internal "github.com/KardFinancial/kard-go-sdk/internal"
	option "github.com/KardFinancial/kard-go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.ClientID == "" {
		options.ClientID = os.Getenv("KARD_CLIENT_ID")
	}
	if options.ClientSecret == "" {
		options.ClientSecret = os.Getenv("KARD_CLIENT_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Call this endpoint to verify network connectivity and service availability.
func (c *Client) Ping(
	ctx context.Context,
	opts ...option.RequestOption,
) (*kardgosdk.PingResponseObject, error) {
	response, err := c.WithRawResponse.Ping(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
