// Code generated by Fern. DO NOT EDIT.

package placements

import (
	context "context"
	os "os"

	kard "github.com/KardFinancial/kard-go-sdk/v11"
	core "github.com/KardFinancial/kard-go-sdk/v11/core"
	internal "github.com/KardFinancial/kard-go-sdk/v11/internal"
	option "github.com/KardFinancial/kard-go-sdk/v11/option"
	organizations "github.com/KardFinancial/kard-go-sdk/v11/organizations"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.ClientID == "" {
		options.ClientID = os.Getenv("KARD_CLIENT_ID")
	}
	if options.ClientSecret == "" {
		options.ClientSecret = os.Getenv("KARD_CLIENT_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Create a placement for the organization. Use type "placementMainPage" for main-page placements (requires name and availableSlots) or "placementPushNotification" for push-notification placements (requires name and cadence; availableSlots is automatically set to 1).
func (c *Client) Create(
	ctx context.Context,
	// Unique identifier of the organization
	organizationId string,
	request *organizations.CreatePlacementRequestBody,
	opts ...option.RequestOption,
) (*organizations.PlacementFormatUnion, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		organizationId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// List placements belonging to the authenticated organization
func (c *Client) List(
	ctx context.Context,
	// Unique identifier of the organization
	organizationId string,
	request *organizations.ListPlacementsRequest,
	opts ...option.RequestOption,
) (*organizations.PlacementListResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		organizationId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a specific placement
func (c *Client) Get(
	ctx context.Context,
	// Unique identifier of the organization
	organizationId string,
	// Unique identifier of the placement (UUID v7)
	placementId string,
	request *organizations.GetPlacementRequest,
	opts ...option.RequestOption,
) (*organizations.PlacementResource, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		organizationId,
		placementId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Replace a placement. All fields must be provided. Use type "placementMainPage" or "placementPushNotification" to set the placement kind. If the type is "placementPushNotification", availableSlots is automatically set to 1.
func (c *Client) Update(
	ctx context.Context,
	// Unique identifier of the organization
	organizationId string,
	// Unique identifier of the placement (UUID v7)
	placementId string,
	request *organizations.UpdatePlacementRequestBody,
	opts ...option.RequestOption,
) (*organizations.PlacementFormatUnion, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		organizationId,
		placementId,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a placement
func (c *Client) Delete(
	ctx context.Context,
	// Unique identifier of the organization
	organizationId string,
	// Unique identifier of the placement (UUID v7)
	placementId string,
	opts ...option.RequestOption,
) (*kard.DeleteResourceResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		organizationId,
		placementId,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
