// Code generated by Fern. DO NOT EDIT.

package files

import (
	context "context"
	http "net/http"

	kard "github.com/KardFinancial/kard-go-sdk/v11"
	core "github.com/KardFinancial/kard-go-sdk/v11/core"
	internal "github.com/KardFinancial/kard-go-sdk/v11/internal"
	option "github.com/KardFinancial/kard-go-sdk/v11/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) GetMetadata(
	ctx context.Context,
	organizationId kard.OrganizationId,
	request *kard.GetFilesMetadataRequest,
	opts ...option.RequestOption,
) (*core.Response[*kard.GetFilesMetadataResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/files/metadata",
		organizationId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *kard.GetFilesMetadataResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(kard.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*kard.GetFilesMetadataResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
