// Code generated by Fern. DO NOT EDIT.

package children

import (
	context "context"
	http "net/http"

	kard "github.com/KardFinancial/kard-go-sdk/v8"
	core "github.com/KardFinancial/kard-go-sdk/v8/core"
	internal "github.com/KardFinancial/kard-go-sdk/v8/internal"
	option "github.com/KardFinancial/kard-go-sdk/v8/option"
	organizations "github.com/KardFinancial/kard-go-sdk/v8/organizations"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	// Unique identifier of the parent organization
	organizationId string,
	request *organizations.ListChildrenRequest,
	opts ...option.RequestOption,
) (*core.Response[*organizations.ChildOrganizationListResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/children",
		organizationId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *organizations.ChildOrganizationListResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(organizations.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*organizations.ChildOrganizationListResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	// Unique identifier of the parent organization
	organizationId string,
	request *organizations.CreateChildRequestBody,
	opts ...option.RequestOption,
) (*core.Response[*organizations.ChildOrganizationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/children",
		organizationId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *organizations.ChildOrganizationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(organizations.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*organizations.ChildOrganizationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Get(
	ctx context.Context,
	// Unique identifier of the parent organization
	organizationId string,
	// Unique identifier of the child organization
	childId string,
	opts ...option.RequestOption,
) (*core.Response[*organizations.ChildOrganizationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/children/%v",
		organizationId,
		childId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *organizations.ChildOrganizationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(organizations.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*organizations.ChildOrganizationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	// Unique identifier of the parent organization
	organizationId string,
	// Unique identifier of the child organization
	childId string,
	request *organizations.UpdateChildRequestBody,
	opts ...option.RequestOption,
) (*core.Response[*organizations.ChildOrganizationResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/children/%v",
		organizationId,
		childId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *organizations.ChildOrganizationResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(organizations.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*organizations.ChildOrganizationResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	// Unique identifier of the parent organization
	organizationId string,
	// Unique identifier of the child organization
	childId string,
	opts ...option.RequestOption,
) (*core.Response[*kard.DeleteResourceResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://rewards-api.getkard.com",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v2/issuers/%v/children/%v",
		organizationId,
		childId,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *kard.DeleteResourceResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(organizations.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*kard.DeleteResourceResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
