// Code generated by Fern. DO NOT EDIT.

package organizations

import (
	json "encoding/json"
	fmt "fmt"
	kardgosdk "github.com/KardFinancial/kard-go-sdk/v5"
	internal "github.com/KardFinancial/kard-go-sdk/v5/internal"
	big "math/big"
)

var (
	getPlacementRequestFieldInclude = big.NewInt(1 << 0)
)

type GetPlacementRequest struct {
	// CSV list of related resources to embed in the `included` array (allowed value is `contentStrategy`).
	Include *string `json:"-" url:"include,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPlacementRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetInclude sets the Include field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPlacementRequest) SetInclude(include *string) {
	g.Include = include
	g.require(getPlacementRequestFieldInclude)
}

var (
	listPlacementsRequestFieldFilterType              = big.NewInt(1 << 0)
	listPlacementsRequestFieldFilterName              = big.NewInt(1 << 1)
	listPlacementsRequestFieldFilterContentStrategyId = big.NewInt(1 << 2)
	listPlacementsRequestFieldInclude                 = big.NewInt(1 << 3)
	listPlacementsRequestFieldPageAfter               = big.NewInt(1 << 4)
	listPlacementsRequestFieldPageSize                = big.NewInt(1 << 5)
)

type ListPlacementsRequest struct {
	// Filter by placement type (placementMainPage or placementPushNotification)
	FilterType *PlacementTypeFilter `json:"-" url:"filter[type],omitempty"`
	// Filter by exact placement name (unique within an organization per type)
	FilterName *string `json:"-" url:"filter[name],omitempty"`
	// Filter by the ID of the content strategy linked to the placement
	FilterContentStrategyId *string `json:"-" url:"filter[contentStrategyId],omitempty"`
	// CSV list of related resources to embed in the `included` array (allowed value is `contentStrategy`).
	Include *string `json:"-" url:"include,omitempty"`
	// Cursor value for the next page of results
	PageAfter *string `json:"-" url:"page[after],omitempty"`
	// Maximum number of records to return [1 - 200] (default = 200)
	PageSize *int `json:"-" url:"page[size],omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListPlacementsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetFilterType sets the FilterType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPlacementsRequest) SetFilterType(filterType *PlacementTypeFilter) {
	l.FilterType = filterType
	l.require(listPlacementsRequestFieldFilterType)
}

// SetFilterName sets the FilterName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPlacementsRequest) SetFilterName(filterName *string) {
	l.FilterName = filterName
	l.require(listPlacementsRequestFieldFilterName)
}

// SetFilterContentStrategyId sets the FilterContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPlacementsRequest) SetFilterContentStrategyId(filterContentStrategyId *string) {
	l.FilterContentStrategyId = filterContentStrategyId
	l.require(listPlacementsRequestFieldFilterContentStrategyId)
}

// SetInclude sets the Include field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPlacementsRequest) SetInclude(include *string) {
	l.Include = include
	l.require(listPlacementsRequestFieldInclude)
}

// SetPageAfter sets the PageAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPlacementsRequest) SetPageAfter(pageAfter *string) {
	l.PageAfter = pageAfter
	l.require(listPlacementsRequestFieldPageAfter)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListPlacementsRequest) SetPageSize(pageSize *int) {
	l.PageSize = pageSize
	l.require(listPlacementsRequestFieldPageSize)
}

// Cadence schedule for push notification placements
var (
	cadenceFieldFrequency  = big.NewInt(1 << 0)
	cadenceFieldTimeOfDay  = big.NewInt(1 << 1)
	cadenceFieldDayOfWeek  = big.NewInt(1 << 2)
	cadenceFieldDayOfMonth = big.NewInt(1 << 3)
)

type Cadence struct {
	// Delivery frequency
	Frequency CadenceFrequency `json:"frequency" url:"frequency"`
	// Optional time of day in HH:mm format (24-hour, UTC)
	TimeOfDay *string `json:"timeOfDay,omitempty" url:"timeOfDay,omitempty"`
	// Day of the week to deliver (used when frequency is WEEKLY, defaults to MON)
	DayOfWeek *DayOfWeek `json:"dayOfWeek,omitempty" url:"dayOfWeek,omitempty"`
	// Day of the month to deliver, 1-31 (used when frequency is MONTHLY, defaults to 1)
	DayOfMonth *int `json:"dayOfMonth,omitempty" url:"dayOfMonth,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *Cadence) GetFrequency() CadenceFrequency {
	if c == nil {
		return ""
	}
	return c.Frequency
}

func (c *Cadence) GetTimeOfDay() *string {
	if c == nil {
		return nil
	}
	return c.TimeOfDay
}

func (c *Cadence) GetDayOfWeek() *DayOfWeek {
	if c == nil {
		return nil
	}
	return c.DayOfWeek
}

func (c *Cadence) GetDayOfMonth() *int {
	if c == nil {
		return nil
	}
	return c.DayOfMonth
}

func (c *Cadence) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *Cadence) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetFrequency sets the Frequency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cadence) SetFrequency(frequency CadenceFrequency) {
	c.Frequency = frequency
	c.require(cadenceFieldFrequency)
}

// SetTimeOfDay sets the TimeOfDay field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cadence) SetTimeOfDay(timeOfDay *string) {
	c.TimeOfDay = timeOfDay
	c.require(cadenceFieldTimeOfDay)
}

// SetDayOfWeek sets the DayOfWeek field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cadence) SetDayOfWeek(dayOfWeek *DayOfWeek) {
	c.DayOfWeek = dayOfWeek
	c.require(cadenceFieldDayOfWeek)
}

// SetDayOfMonth sets the DayOfMonth field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *Cadence) SetDayOfMonth(dayOfMonth *int) {
	c.DayOfMonth = dayOfMonth
	c.require(cadenceFieldDayOfMonth)
}

func (c *Cadence) UnmarshalJSON(data []byte) error {
	type unmarshaler Cadence
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = Cadence(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *Cadence) MarshalJSON() ([]byte, error) {
	type embed Cadence
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *Cadence) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// How often a push notification placement delivers
type CadenceFrequency string

const (
	CadenceFrequencyDaily   CadenceFrequency = "DAILY"
	CadenceFrequencyWeekly  CadenceFrequency = "WEEKLY"
	CadenceFrequencyMonthly CadenceFrequency = "MONTHLY"
)

func NewCadenceFrequencyFromString(s string) (CadenceFrequency, error) {
	switch s {
	case "DAILY":
		return CadenceFrequencyDaily, nil
	case "WEEKLY":
		return CadenceFrequencyWeekly, nil
	case "MONTHLY":
		return CadenceFrequencyMonthly, nil
	}
	var t CadenceFrequency
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CadenceFrequency) Ptr() *CadenceFrequency {
	return &c
}

// Attributes for creating a main-page placement
var (
	createMainPageAttributesFieldName              = big.NewInt(1 << 0)
	createMainPageAttributesFieldAvailableSlots    = big.NewInt(1 << 1)
	createMainPageAttributesFieldContentStrategyId = big.NewInt(1 << 2)
)

type CreateMainPageAttributes struct {
	// Name of the placement
	Name string `json:"name" url:"name"`
	// Number of available slots (minimum 1)
	AvailableSlots int `json:"availableSlots" url:"availableSlots"`
	// ID of the content strategy to link this placement to
	ContentStrategyId *string `json:"contentStrategyId,omitempty" url:"contentStrategyId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMainPageAttributes) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateMainPageAttributes) GetAvailableSlots() int {
	if c == nil {
		return 0
	}
	return c.AvailableSlots
}

func (c *CreateMainPageAttributes) GetContentStrategyId() *string {
	if c == nil {
		return nil
	}
	return c.ContentStrategyId
}

func (c *CreateMainPageAttributes) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateMainPageAttributes) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMainPageAttributes) SetName(name string) {
	c.Name = name
	c.require(createMainPageAttributesFieldName)
}

// SetAvailableSlots sets the AvailableSlots field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMainPageAttributes) SetAvailableSlots(availableSlots int) {
	c.AvailableSlots = availableSlots
	c.require(createMainPageAttributesFieldAvailableSlots)
}

// SetContentStrategyId sets the ContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMainPageAttributes) SetContentStrategyId(contentStrategyId *string) {
	c.ContentStrategyId = contentStrategyId
	c.require(createMainPageAttributesFieldContentStrategyId)
}

func (c *CreateMainPageAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMainPageAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMainPageAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMainPageAttributes) MarshalJSON() ([]byte, error) {
	type embed CreateMainPageAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMainPageAttributes) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Data for creating a main-page placement
var (
	createMainPagePlacementDataFieldAttributes = big.NewInt(1 << 0)
)

type CreateMainPagePlacementData struct {
	// Main-page placement attributes for creation
	Attributes *CreateMainPageAttributes `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateMainPagePlacementData) GetAttributes() *CreateMainPageAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

func (c *CreateMainPagePlacementData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateMainPagePlacementData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateMainPagePlacementData) SetAttributes(attributes *CreateMainPageAttributes) {
	c.Attributes = attributes
	c.require(createMainPagePlacementDataFieldAttributes)
}

func (c *CreateMainPagePlacementData) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateMainPagePlacementData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateMainPagePlacementData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateMainPagePlacementData) MarshalJSON() ([]byte, error) {
	type embed CreateMainPagePlacementData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateMainPagePlacementData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Discriminated union for creating a placement
type CreatePlacementDataUnion struct {
	Type                      string
	PlacementMainPage         *CreateMainPagePlacementData
	PlacementPushNotification *CreatePushNotificationPlacementData
}

func (c *CreatePlacementDataUnion) GetType() string {
	if c == nil {
		return ""
	}
	return c.Type
}

func (c *CreatePlacementDataUnion) GetPlacementMainPage() *CreateMainPagePlacementData {
	if c == nil {
		return nil
	}
	return c.PlacementMainPage
}

func (c *CreatePlacementDataUnion) GetPlacementPushNotification() *CreatePushNotificationPlacementData {
	if c == nil {
		return nil
	}
	return c.PlacementPushNotification
}

func (c *CreatePlacementDataUnion) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	c.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", c)
	}
	switch unmarshaler.Type {
	case "placementMainPage":
		value := new(CreateMainPagePlacementData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.PlacementMainPage = value
	case "placementPushNotification":
		value := new(CreatePushNotificationPlacementData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		c.PlacementPushNotification = value
	}
	return nil
}

func (c CreatePlacementDataUnion) MarshalJSON() ([]byte, error) {
	if err := c.validate(); err != nil {
		return nil, err
	}
	if c.PlacementMainPage != nil {
		return internal.MarshalJSONWithExtraProperty(c.PlacementMainPage, "type", "placementMainPage")
	}
	if c.PlacementPushNotification != nil {
		return internal.MarshalJSONWithExtraProperty(c.PlacementPushNotification, "type", "placementPushNotification")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", c)
}

type CreatePlacementDataUnionVisitor interface {
	VisitPlacementMainPage(*CreateMainPagePlacementData) error
	VisitPlacementPushNotification(*CreatePushNotificationPlacementData) error
}

func (c *CreatePlacementDataUnion) Accept(visitor CreatePlacementDataUnionVisitor) error {
	if c.PlacementMainPage != nil {
		return visitor.VisitPlacementMainPage(c.PlacementMainPage)
	}
	if c.PlacementPushNotification != nil {
		return visitor.VisitPlacementPushNotification(c.PlacementPushNotification)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", c)
}

func (c *CreatePlacementDataUnion) validate() error {
	if c == nil {
		return fmt.Errorf("type %T is nil", c)
	}
	var fields []string
	if c.PlacementMainPage != nil {
		fields = append(fields, "placementMainPage")
	}
	if c.PlacementPushNotification != nil {
		fields = append(fields, "placementPushNotification")
	}
	if len(fields) == 0 {
		if c.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", c, c.Type)
		}
		return fmt.Errorf("type %T is empty", c)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", c, fields)
	}
	if c.Type != "" {
		field := fields[0]
		if c.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				c,
				c.Type,
				c,
			)
		}
	}
	return nil
}

// Request body for creating a placement
var (
	createPlacementRequestBodyFieldData = big.NewInt(1 << 0)
)

type CreatePlacementRequestBody struct {
	// Placement data for creation
	Data *CreatePlacementDataUnion `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePlacementRequestBody) GetData() *CreatePlacementDataUnion {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreatePlacementRequestBody) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePlacementRequestBody) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePlacementRequestBody) SetData(data *CreatePlacementDataUnion) {
	c.Data = data
	c.require(createPlacementRequestBodyFieldData)
}

func (c *CreatePlacementRequestBody) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePlacementRequestBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePlacementRequestBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePlacementRequestBody) MarshalJSON() ([]byte, error) {
	type embed CreatePlacementRequestBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePlacementRequestBody) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Attributes for creating a push-notification placement
var (
	createPushNotificationAttributesFieldName              = big.NewInt(1 << 0)
	createPushNotificationAttributesFieldCadence           = big.NewInt(1 << 1)
	createPushNotificationAttributesFieldContentStrategyId = big.NewInt(1 << 2)
)

type CreatePushNotificationAttributes struct {
	// Name of the placement
	Name string `json:"name" url:"name"`
	// Delivery cadence for the notification
	Cadence *Cadence `json:"cadence" url:"cadence"`
	// ID of the content strategy to link this placement to
	ContentStrategyId *string `json:"contentStrategyId,omitempty" url:"contentStrategyId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePushNotificationAttributes) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreatePushNotificationAttributes) GetCadence() *Cadence {
	if c == nil {
		return nil
	}
	return c.Cadence
}

func (c *CreatePushNotificationAttributes) GetContentStrategyId() *string {
	if c == nil {
		return nil
	}
	return c.ContentStrategyId
}

func (c *CreatePushNotificationAttributes) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePushNotificationAttributes) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePushNotificationAttributes) SetName(name string) {
	c.Name = name
	c.require(createPushNotificationAttributesFieldName)
}

// SetCadence sets the Cadence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePushNotificationAttributes) SetCadence(cadence *Cadence) {
	c.Cadence = cadence
	c.require(createPushNotificationAttributesFieldCadence)
}

// SetContentStrategyId sets the ContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePushNotificationAttributes) SetContentStrategyId(contentStrategyId *string) {
	c.ContentStrategyId = contentStrategyId
	c.require(createPushNotificationAttributesFieldContentStrategyId)
}

func (c *CreatePushNotificationAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePushNotificationAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePushNotificationAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePushNotificationAttributes) MarshalJSON() ([]byte, error) {
	type embed CreatePushNotificationAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePushNotificationAttributes) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Data for creating a push-notification placement
var (
	createPushNotificationPlacementDataFieldAttributes = big.NewInt(1 << 0)
)

type CreatePushNotificationPlacementData struct {
	// Push-notification placement attributes for creation
	Attributes *CreatePushNotificationAttributes `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreatePushNotificationPlacementData) GetAttributes() *CreatePushNotificationAttributes {
	if c == nil {
		return nil
	}
	return c.Attributes
}

func (c *CreatePushNotificationPlacementData) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreatePushNotificationPlacementData) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePushNotificationPlacementData) SetAttributes(attributes *CreatePushNotificationAttributes) {
	c.Attributes = attributes
	c.require(createPushNotificationPlacementDataFieldAttributes)
}

func (c *CreatePushNotificationPlacementData) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePushNotificationPlacementData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreatePushNotificationPlacementData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreatePushNotificationPlacementData) MarshalJSON() ([]byte, error) {
	type embed CreatePushNotificationPlacementData
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreatePushNotificationPlacementData) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Day of the week (used when frequency is WEEKLY)
type DayOfWeek string

const (
	DayOfWeekMon DayOfWeek = "MON"
	DayOfWeekTue DayOfWeek = "TUE"
	DayOfWeekWed DayOfWeek = "WED"
	DayOfWeekThu DayOfWeek = "THU"
	DayOfWeekFri DayOfWeek = "FRI"
	DayOfWeekSat DayOfWeek = "SAT"
	DayOfWeekSun DayOfWeek = "SUN"
)

func NewDayOfWeekFromString(s string) (DayOfWeek, error) {
	switch s {
	case "MON":
		return DayOfWeekMon, nil
	case "TUE":
		return DayOfWeekTue, nil
	case "WED":
		return DayOfWeekWed, nil
	case "THU":
		return DayOfWeekThu, nil
	case "FRI":
		return DayOfWeekFri, nil
	case "SAT":
		return DayOfWeekSat, nil
	case "SUN":
		return DayOfWeekSun, nil
	}
	var t DayOfWeek
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DayOfWeek) Ptr() *DayOfWeek {
	return &d
}

// Attributes for a main-page placement
var (
	mainPagePlacementAttributesFieldName              = big.NewInt(1 << 0)
	mainPagePlacementAttributesFieldOrganizationId    = big.NewInt(1 << 1)
	mainPagePlacementAttributesFieldAvailableSlots    = big.NewInt(1 << 2)
	mainPagePlacementAttributesFieldContentStrategyId = big.NewInt(1 << 3)
)

type MainPagePlacementAttributes struct {
	// Name of the placement
	Name string `json:"name" url:"name"`
	// ID of the organization this placement belongs to
	OrganizationId string `json:"organizationId" url:"organizationId"`
	// Number of available slots
	AvailableSlots int `json:"availableSlots" url:"availableSlots"`
	// ID of the content strategy linked to this placement, if any
	ContentStrategyId *string `json:"contentStrategyId,omitempty" url:"contentStrategyId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MainPagePlacementAttributes) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *MainPagePlacementAttributes) GetOrganizationId() string {
	if m == nil {
		return ""
	}
	return m.OrganizationId
}

func (m *MainPagePlacementAttributes) GetAvailableSlots() int {
	if m == nil {
		return 0
	}
	return m.AvailableSlots
}

func (m *MainPagePlacementAttributes) GetContentStrategyId() *string {
	if m == nil {
		return nil
	}
	return m.ContentStrategyId
}

func (m *MainPagePlacementAttributes) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MainPagePlacementAttributes) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MainPagePlacementAttributes) SetName(name string) {
	m.Name = name
	m.require(mainPagePlacementAttributesFieldName)
}

// SetOrganizationId sets the OrganizationId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MainPagePlacementAttributes) SetOrganizationId(organizationId string) {
	m.OrganizationId = organizationId
	m.require(mainPagePlacementAttributesFieldOrganizationId)
}

// SetAvailableSlots sets the AvailableSlots field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MainPagePlacementAttributes) SetAvailableSlots(availableSlots int) {
	m.AvailableSlots = availableSlots
	m.require(mainPagePlacementAttributesFieldAvailableSlots)
}

// SetContentStrategyId sets the ContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MainPagePlacementAttributes) SetContentStrategyId(contentStrategyId *string) {
	m.ContentStrategyId = contentStrategyId
	m.require(mainPagePlacementAttributesFieldContentStrategyId)
}

func (m *MainPagePlacementAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler MainPagePlacementAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MainPagePlacementAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MainPagePlacementAttributes) MarshalJSON() ([]byte, error) {
	type embed MainPagePlacementAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MainPagePlacementAttributes) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// Main-page placement resource data
var (
	mainPagePlacementDataFieldId         = big.NewInt(1 << 0)
	mainPagePlacementDataFieldAttributes = big.NewInt(1 << 1)
)

type MainPagePlacementData struct {
	// Unique identifier of the placement (UUID v7)
	Id         string                       `json:"id" url:"id"`
	Attributes *MainPagePlacementAttributes `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MainPagePlacementData) GetId() string {
	if m == nil {
		return ""
	}
	return m.Id
}

func (m *MainPagePlacementData) GetAttributes() *MainPagePlacementAttributes {
	if m == nil {
		return nil
	}
	return m.Attributes
}

func (m *MainPagePlacementData) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MainPagePlacementData) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MainPagePlacementData) SetId(id string) {
	m.Id = id
	m.require(mainPagePlacementDataFieldId)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MainPagePlacementData) SetAttributes(attributes *MainPagePlacementAttributes) {
	m.Attributes = attributes
	m.require(mainPagePlacementDataFieldAttributes)
}

func (m *MainPagePlacementData) UnmarshalJSON(data []byte) error {
	type unmarshaler MainPagePlacementData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MainPagePlacementData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MainPagePlacementData) MarshalJSON() ([]byte, error) {
	type embed MainPagePlacementData
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MainPagePlacementData) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

// Discriminated union for placement resources keyed on type
type PlacementFormatUnion struct {
	Type                      string
	PlacementMainPage         *MainPagePlacementData
	PlacementPushNotification *PushNotificationPlacementData
}

func (p *PlacementFormatUnion) GetType() string {
	if p == nil {
		return ""
	}
	return p.Type
}

func (p *PlacementFormatUnion) GetPlacementMainPage() *MainPagePlacementData {
	if p == nil {
		return nil
	}
	return p.PlacementMainPage
}

func (p *PlacementFormatUnion) GetPlacementPushNotification() *PushNotificationPlacementData {
	if p == nil {
		return nil
	}
	return p.PlacementPushNotification
}

func (p *PlacementFormatUnion) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	p.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", p)
	}
	switch unmarshaler.Type {
	case "placementMainPage":
		value := new(MainPagePlacementData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.PlacementMainPage = value
	case "placementPushNotification":
		value := new(PushNotificationPlacementData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.PlacementPushNotification = value
	}
	return nil
}

func (p PlacementFormatUnion) MarshalJSON() ([]byte, error) {
	if err := p.validate(); err != nil {
		return nil, err
	}
	if p.PlacementMainPage != nil {
		return internal.MarshalJSONWithExtraProperty(p.PlacementMainPage, "type", "placementMainPage")
	}
	if p.PlacementPushNotification != nil {
		return internal.MarshalJSONWithExtraProperty(p.PlacementPushNotification, "type", "placementPushNotification")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", p)
}

type PlacementFormatUnionVisitor interface {
	VisitPlacementMainPage(*MainPagePlacementData) error
	VisitPlacementPushNotification(*PushNotificationPlacementData) error
}

func (p *PlacementFormatUnion) Accept(visitor PlacementFormatUnionVisitor) error {
	if p.PlacementMainPage != nil {
		return visitor.VisitPlacementMainPage(p.PlacementMainPage)
	}
	if p.PlacementPushNotification != nil {
		return visitor.VisitPlacementPushNotification(p.PlacementPushNotification)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", p)
}

func (p *PlacementFormatUnion) validate() error {
	if p == nil {
		return fmt.Errorf("type %T is nil", p)
	}
	var fields []string
	if p.PlacementMainPage != nil {
		fields = append(fields, "placementMainPage")
	}
	if p.PlacementPushNotification != nil {
		fields = append(fields, "placementPushNotification")
	}
	if len(fields) == 0 {
		if p.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", p, p.Type)
		}
		return fmt.Errorf("type %T is empty", p)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", p, fields)
	}
	if p.Type != "" {
		field := fields[0]
		if p.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				p,
				p.Type,
				p,
			)
		}
	}
	return nil
}

// Paginated list of placements
var (
	placementListResponseFieldData     = big.NewInt(1 << 0)
	placementListResponseFieldIncluded = big.NewInt(1 << 1)
	placementListResponseFieldLinks    = big.NewInt(1 << 2)
	placementListResponseFieldMeta     = big.NewInt(1 << 3)
)

type PlacementListResponse struct {
	// Array of placement resources
	Data []*PlacementFormatUnion `json:"data" url:"data"`
	// Related resources requested via the `include` query parameter. Only populated when `include=contentStrategy` is supplied and at least one placement in `data` is linked to a content strategy.
	Included []*ContentStrategyResponse `json:"included,omitempty" url:"included,omitempty"`
	Links    *kardgosdk.Links           `json:"links,omitempty" url:"links,omitempty"`
	// Pagination metadata
	Meta *kardgosdk.OrganizationPaginationMetadata `json:"meta,omitempty" url:"meta,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlacementListResponse) GetData() []*PlacementFormatUnion {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PlacementListResponse) GetIncluded() []*ContentStrategyResponse {
	if p == nil {
		return nil
	}
	return p.Included
}

func (p *PlacementListResponse) GetLinks() *kardgosdk.Links {
	if p == nil {
		return nil
	}
	return p.Links
}

func (p *PlacementListResponse) GetMeta() *kardgosdk.OrganizationPaginationMetadata {
	if p == nil {
		return nil
	}
	return p.Meta
}

func (p *PlacementListResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PlacementListResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlacementListResponse) SetData(data []*PlacementFormatUnion) {
	p.Data = data
	p.require(placementListResponseFieldData)
}

// SetIncluded sets the Included field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlacementListResponse) SetIncluded(included []*ContentStrategyResponse) {
	p.Included = included
	p.require(placementListResponseFieldIncluded)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlacementListResponse) SetLinks(links *kardgosdk.Links) {
	p.Links = links
	p.require(placementListResponseFieldLinks)
}

// SetMeta sets the Meta field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlacementListResponse) SetMeta(meta *kardgosdk.OrganizationPaginationMetadata) {
	p.Meta = meta
	p.require(placementListResponseFieldMeta)
}

func (p *PlacementListResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PlacementListResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlacementListResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlacementListResponse) MarshalJSON() ([]byte, error) {
	type embed PlacementListResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PlacementListResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Single placement document, optionally with embedded related resources
var (
	placementResourceFieldData     = big.NewInt(1 << 0)
	placementResourceFieldIncluded = big.NewInt(1 << 1)
)

type PlacementResource struct {
	// Placement resource
	Data *PlacementFormatUnion `json:"data" url:"data"`
	// Related resources requested via the `include` query parameter. Only populated when `include=contentStrategy` is supplied and the placement is linked to a content strategy.
	Included []*ContentStrategyResponse `json:"included,omitempty" url:"included,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PlacementResource) GetData() *PlacementFormatUnion {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PlacementResource) GetIncluded() []*ContentStrategyResponse {
	if p == nil {
		return nil
	}
	return p.Included
}

func (p *PlacementResource) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PlacementResource) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlacementResource) SetData(data *PlacementFormatUnion) {
	p.Data = data
	p.require(placementResourceFieldData)
}

// SetIncluded sets the Included field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlacementResource) SetIncluded(included []*ContentStrategyResponse) {
	p.Included = included
	p.require(placementResourceFieldIncluded)
}

func (p *PlacementResource) UnmarshalJSON(data []byte) error {
	type unmarshaler PlacementResource
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PlacementResource(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PlacementResource) MarshalJSON() ([]byte, error) {
	type embed PlacementResource
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PlacementResource) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Placement type discriminator used as a list filter
type PlacementTypeFilter string

const (
	PlacementTypeFilterPlacementMainPage         PlacementTypeFilter = "placementMainPage"
	PlacementTypeFilterPlacementPushNotification PlacementTypeFilter = "placementPushNotification"
)

func NewPlacementTypeFilterFromString(s string) (PlacementTypeFilter, error) {
	switch s {
	case "placementMainPage":
		return PlacementTypeFilterPlacementMainPage, nil
	case "placementPushNotification":
		return PlacementTypeFilterPlacementPushNotification, nil
	}
	var t PlacementTypeFilter
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PlacementTypeFilter) Ptr() *PlacementTypeFilter {
	return &p
}

// Attributes for a push-notification placement
var (
	pushNotificationPlacementAttributesFieldName              = big.NewInt(1 << 0)
	pushNotificationPlacementAttributesFieldOrganizationId    = big.NewInt(1 << 1)
	pushNotificationPlacementAttributesFieldCadence           = big.NewInt(1 << 2)
	pushNotificationPlacementAttributesFieldContentStrategyId = big.NewInt(1 << 3)
)

type PushNotificationPlacementAttributes struct {
	// Name of the placement
	Name string `json:"name" url:"name"`
	// ID of the organization this placement belongs to
	OrganizationId string `json:"organizationId" url:"organizationId"`
	// Delivery cadence for the notification
	Cadence *Cadence `json:"cadence" url:"cadence"`
	// ID of the content strategy linked to this placement, if any
	ContentStrategyId *string `json:"contentStrategyId,omitempty" url:"contentStrategyId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PushNotificationPlacementAttributes) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PushNotificationPlacementAttributes) GetOrganizationId() string {
	if p == nil {
		return ""
	}
	return p.OrganizationId
}

func (p *PushNotificationPlacementAttributes) GetCadence() *Cadence {
	if p == nil {
		return nil
	}
	return p.Cadence
}

func (p *PushNotificationPlacementAttributes) GetContentStrategyId() *string {
	if p == nil {
		return nil
	}
	return p.ContentStrategyId
}

func (p *PushNotificationPlacementAttributes) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PushNotificationPlacementAttributes) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PushNotificationPlacementAttributes) SetName(name string) {
	p.Name = name
	p.require(pushNotificationPlacementAttributesFieldName)
}

// SetOrganizationId sets the OrganizationId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PushNotificationPlacementAttributes) SetOrganizationId(organizationId string) {
	p.OrganizationId = organizationId
	p.require(pushNotificationPlacementAttributesFieldOrganizationId)
}

// SetCadence sets the Cadence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PushNotificationPlacementAttributes) SetCadence(cadence *Cadence) {
	p.Cadence = cadence
	p.require(pushNotificationPlacementAttributesFieldCadence)
}

// SetContentStrategyId sets the ContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PushNotificationPlacementAttributes) SetContentStrategyId(contentStrategyId *string) {
	p.ContentStrategyId = contentStrategyId
	p.require(pushNotificationPlacementAttributesFieldContentStrategyId)
}

func (p *PushNotificationPlacementAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler PushNotificationPlacementAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PushNotificationPlacementAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PushNotificationPlacementAttributes) MarshalJSON() ([]byte, error) {
	type embed PushNotificationPlacementAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PushNotificationPlacementAttributes) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Push-notification placement resource data
var (
	pushNotificationPlacementDataFieldId         = big.NewInt(1 << 0)
	pushNotificationPlacementDataFieldAttributes = big.NewInt(1 << 1)
)

type PushNotificationPlacementData struct {
	// Unique identifier of the placement (UUID v7)
	Id         string                               `json:"id" url:"id"`
	Attributes *PushNotificationPlacementAttributes `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PushNotificationPlacementData) GetId() string {
	if p == nil {
		return ""
	}
	return p.Id
}

func (p *PushNotificationPlacementData) GetAttributes() *PushNotificationPlacementAttributes {
	if p == nil {
		return nil
	}
	return p.Attributes
}

func (p *PushNotificationPlacementData) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PushNotificationPlacementData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PushNotificationPlacementData) SetId(id string) {
	p.Id = id
	p.require(pushNotificationPlacementDataFieldId)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PushNotificationPlacementData) SetAttributes(attributes *PushNotificationPlacementAttributes) {
	p.Attributes = attributes
	p.require(pushNotificationPlacementDataFieldAttributes)
}

func (p *PushNotificationPlacementData) UnmarshalJSON(data []byte) error {
	type unmarshaler PushNotificationPlacementData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PushNotificationPlacementData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PushNotificationPlacementData) MarshalJSON() ([]byte, error) {
	type embed PushNotificationPlacementData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PushNotificationPlacementData) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Attributes for updating a main-page placement. All fields are required.
var (
	updateMainPageAttributesFieldName              = big.NewInt(1 << 0)
	updateMainPageAttributesFieldAvailableSlots    = big.NewInt(1 << 1)
	updateMainPageAttributesFieldContentStrategyId = big.NewInt(1 << 2)
)

type UpdateMainPageAttributes struct {
	// Name of the placement
	Name string `json:"name" url:"name"`
	// Number of available slots (minimum 1)
	AvailableSlots int `json:"availableSlots" url:"availableSlots"`
	// ID of the content strategy to link this placement to. Omit to clear any existing link (PUT requires the full attribute set, so a missing value unlinks the placement).
	ContentStrategyId *string `json:"contentStrategyId,omitempty" url:"contentStrategyId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateMainPageAttributes) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateMainPageAttributes) GetAvailableSlots() int {
	if u == nil {
		return 0
	}
	return u.AvailableSlots
}

func (u *UpdateMainPageAttributes) GetContentStrategyId() *string {
	if u == nil {
		return nil
	}
	return u.ContentStrategyId
}

func (u *UpdateMainPageAttributes) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateMainPageAttributes) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMainPageAttributes) SetName(name string) {
	u.Name = name
	u.require(updateMainPageAttributesFieldName)
}

// SetAvailableSlots sets the AvailableSlots field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMainPageAttributes) SetAvailableSlots(availableSlots int) {
	u.AvailableSlots = availableSlots
	u.require(updateMainPageAttributesFieldAvailableSlots)
}

// SetContentStrategyId sets the ContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMainPageAttributes) SetContentStrategyId(contentStrategyId *string) {
	u.ContentStrategyId = contentStrategyId
	u.require(updateMainPageAttributesFieldContentStrategyId)
}

func (u *UpdateMainPageAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMainPageAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateMainPageAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateMainPageAttributes) MarshalJSON() ([]byte, error) {
	type embed UpdateMainPageAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateMainPageAttributes) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Data for updating a main-page placement
var (
	updateMainPagePlacementDataFieldAttributes = big.NewInt(1 << 0)
)

type UpdateMainPagePlacementData struct {
	// Main-page placement attributes for update
	Attributes *UpdateMainPageAttributes `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateMainPagePlacementData) GetAttributes() *UpdateMainPageAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}

func (u *UpdateMainPagePlacementData) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateMainPagePlacementData) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMainPagePlacementData) SetAttributes(attributes *UpdateMainPageAttributes) {
	u.Attributes = attributes
	u.require(updateMainPagePlacementDataFieldAttributes)
}

func (u *UpdateMainPagePlacementData) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMainPagePlacementData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateMainPagePlacementData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateMainPagePlacementData) MarshalJSON() ([]byte, error) {
	type embed UpdateMainPagePlacementData
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateMainPagePlacementData) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Discriminated union for updating a placement
type UpdatePlacementDataUnion struct {
	Type                      string
	PlacementMainPage         *UpdateMainPagePlacementData
	PlacementPushNotification *UpdatePushNotificationPlacementData
}

func (u *UpdatePlacementDataUnion) GetType() string {
	if u == nil {
		return ""
	}
	return u.Type
}

func (u *UpdatePlacementDataUnion) GetPlacementMainPage() *UpdateMainPagePlacementData {
	if u == nil {
		return nil
	}
	return u.PlacementMainPage
}

func (u *UpdatePlacementDataUnion) GetPlacementPushNotification() *UpdatePushNotificationPlacementData {
	if u == nil {
		return nil
	}
	return u.PlacementPushNotification
}

func (u *UpdatePlacementDataUnion) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	u.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", u)
	}
	switch unmarshaler.Type {
	case "placementMainPage":
		value := new(UpdateMainPagePlacementData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		u.PlacementMainPage = value
	case "placementPushNotification":
		value := new(UpdatePushNotificationPlacementData)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		u.PlacementPushNotification = value
	}
	return nil
}

func (u UpdatePlacementDataUnion) MarshalJSON() ([]byte, error) {
	if err := u.validate(); err != nil {
		return nil, err
	}
	if u.PlacementMainPage != nil {
		return internal.MarshalJSONWithExtraProperty(u.PlacementMainPage, "type", "placementMainPage")
	}
	if u.PlacementPushNotification != nil {
		return internal.MarshalJSONWithExtraProperty(u.PlacementPushNotification, "type", "placementPushNotification")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", u)
}

type UpdatePlacementDataUnionVisitor interface {
	VisitPlacementMainPage(*UpdateMainPagePlacementData) error
	VisitPlacementPushNotification(*UpdatePushNotificationPlacementData) error
}

func (u *UpdatePlacementDataUnion) Accept(visitor UpdatePlacementDataUnionVisitor) error {
	if u.PlacementMainPage != nil {
		return visitor.VisitPlacementMainPage(u.PlacementMainPage)
	}
	if u.PlacementPushNotification != nil {
		return visitor.VisitPlacementPushNotification(u.PlacementPushNotification)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", u)
}

func (u *UpdatePlacementDataUnion) validate() error {
	if u == nil {
		return fmt.Errorf("type %T is nil", u)
	}
	var fields []string
	if u.PlacementMainPage != nil {
		fields = append(fields, "placementMainPage")
	}
	if u.PlacementPushNotification != nil {
		fields = append(fields, "placementPushNotification")
	}
	if len(fields) == 0 {
		if u.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", u, u.Type)
		}
		return fmt.Errorf("type %T is empty", u)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", u, fields)
	}
	if u.Type != "" {
		field := fields[0]
		if u.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				u,
				u.Type,
				u,
			)
		}
	}
	return nil
}

// Request body for updating a placement
var (
	updatePlacementRequestBodyFieldData = big.NewInt(1 << 0)
)

type UpdatePlacementRequestBody struct {
	// Placement data for update
	Data *UpdatePlacementDataUnion `json:"data" url:"data"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePlacementRequestBody) GetData() *UpdatePlacementDataUnion {
	if u == nil {
		return nil
	}
	return u.Data
}

func (u *UpdatePlacementRequestBody) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePlacementRequestBody) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePlacementRequestBody) SetData(data *UpdatePlacementDataUnion) {
	u.Data = data
	u.require(updatePlacementRequestBodyFieldData)
}

func (u *UpdatePlacementRequestBody) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePlacementRequestBody
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePlacementRequestBody(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePlacementRequestBody) MarshalJSON() ([]byte, error) {
	type embed UpdatePlacementRequestBody
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePlacementRequestBody) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Attributes for updating a push-notification placement. All fields are required.
var (
	updatePushNotificationAttributesFieldName              = big.NewInt(1 << 0)
	updatePushNotificationAttributesFieldCadence           = big.NewInt(1 << 1)
	updatePushNotificationAttributesFieldContentStrategyId = big.NewInt(1 << 2)
)

type UpdatePushNotificationAttributes struct {
	// Name of the placement
	Name string `json:"name" url:"name"`
	// Delivery cadence for the notification
	Cadence *Cadence `json:"cadence" url:"cadence"`
	// ID of the content strategy to link this placement to. Omit to clear any existing link (PUT requires the full attribute set, so a missing value unlinks the placement).
	ContentStrategyId *string `json:"contentStrategyId,omitempty" url:"contentStrategyId,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePushNotificationAttributes) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdatePushNotificationAttributes) GetCadence() *Cadence {
	if u == nil {
		return nil
	}
	return u.Cadence
}

func (u *UpdatePushNotificationAttributes) GetContentStrategyId() *string {
	if u == nil {
		return nil
	}
	return u.ContentStrategyId
}

func (u *UpdatePushNotificationAttributes) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePushNotificationAttributes) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePushNotificationAttributes) SetName(name string) {
	u.Name = name
	u.require(updatePushNotificationAttributesFieldName)
}

// SetCadence sets the Cadence field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePushNotificationAttributes) SetCadence(cadence *Cadence) {
	u.Cadence = cadence
	u.require(updatePushNotificationAttributesFieldCadence)
}

// SetContentStrategyId sets the ContentStrategyId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePushNotificationAttributes) SetContentStrategyId(contentStrategyId *string) {
	u.ContentStrategyId = contentStrategyId
	u.require(updatePushNotificationAttributesFieldContentStrategyId)
}

func (u *UpdatePushNotificationAttributes) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePushNotificationAttributes
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePushNotificationAttributes(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePushNotificationAttributes) MarshalJSON() ([]byte, error) {
	type embed UpdatePushNotificationAttributes
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePushNotificationAttributes) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// Data for updating a push-notification placement
var (
	updatePushNotificationPlacementDataFieldAttributes = big.NewInt(1 << 0)
)

type UpdatePushNotificationPlacementData struct {
	// Push-notification placement attributes for update
	Attributes *UpdatePushNotificationAttributes `json:"attributes" url:"attributes"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdatePushNotificationPlacementData) GetAttributes() *UpdatePushNotificationAttributes {
	if u == nil {
		return nil
	}
	return u.Attributes
}

func (u *UpdatePushNotificationPlacementData) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdatePushNotificationPlacementData) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAttributes sets the Attributes field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdatePushNotificationPlacementData) SetAttributes(attributes *UpdatePushNotificationAttributes) {
	u.Attributes = attributes
	u.require(updatePushNotificationPlacementDataFieldAttributes)
}

func (u *UpdatePushNotificationPlacementData) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdatePushNotificationPlacementData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdatePushNotificationPlacementData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdatePushNotificationPlacementData) MarshalJSON() ([]byte, error) {
	type embed UpdatePushNotificationPlacementData
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdatePushNotificationPlacementData) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
